// Builds study-tool-picks.js: the AI tools that AI Study suggests after a result, copied from the reviewed
// catalog (data.js + september-2026-tool-audit.js) so names, links and age rules have one source of truth.
// Usage: node scripts/study-tool-picks/build.cjs   (tests/study-tool-picks-smoke.mjs fails if the copy drifts)
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const ROOT = path.resolve(__dirname, "../..");

function loadCatalog() {
  const noop = () => {};
  const c = { console, requestAnimationFrame: noop, setTimeout: noop, location: { pathname: "/" },
    document: { querySelectorAll: () => [], querySelector: () => null, addEventListener: noop, getElementById: () => null, documentElement: { lang: "el" } } };
  c.window = c; c.addEventListener = noop;
  vm.createContext(c);
  vm.runInContext(fs.readFileSync(path.join(ROOT, "data.js"), "utf8") + ";" + fs.readFileSync(path.join(ROOT, "september-2026-tool-audit.js"), "utf8") + ";this.__T=TOOLS", c);
  return c.__T;
}

const IDS = ["notebooklm", "chatgpt", "quizlet", "anki", "astra-ai", "daskalakos-ai", "immersive-reader", "reading-coach",
  "geogebra", "desmos", "phet", "google-arts-culture", "google-earth", "deepl", "scratch", "mindmup"];

function picksData(T = loadCatalog()) {
  const tools = {};
  for (const id of IDS) {
    const t = T[id];
    if (!t) throw new Error("tool missing from catalog: " + id);
    tools[id] = { name: t.name, url: t.url, minAge: Number.isInteger(t.minAge) ? t.minAge : 0,
      parentAccountRequired: !!t.parentAccountRequired, el: t.shortDescEl, en: t.shortDescEn, reviewed: t.lastReviewed || "" };
  }
  return tools;
}

function render(tools) {
  const src = fs.readFileSync(path.join(ROOT, "study-tool-picks.js"), "utf8");
  const json = JSON.stringify(tools, null, 1).replace(/\n/g, "\n  ");
  return src.replace(/\/\/ TOOLS-BEGIN[\s\S]*?\/\/ TOOLS-END/, `// TOOLS-BEGIN (generated by scripts/study-tool-picks/build.cjs)\n  const TOOLS = ${json};\n  // TOOLS-END`);
}

if (require.main === module) {
  fs.writeFileSync(path.join(ROOT, "study-tool-picks.js"), render(picksData()));
  console.log("study-tool-picks.js updated:", IDS.length, "tools");
}
module.exports = { loadCatalog, picksData, render, IDS };
