/**
 * data.js
 * ------------------------------------------------------------
 * Πηγή δεδομένων για το AI Tools for Family, Kids & Students.
 * 
 * ΕΚΔΟΣΗ: Ελληνική προσαρμογή 2026
 * ------------------------------------------------------------
 */

// ---------- ΖΩΝΕΣ ----------
const ZONES = [
  {
    id: "primary",
    icon: "🧒",
    labelEl: "Δημοτικό",
    labelEn: "Primary",
    ageRangeEl: "6 έως 12 ετών",
    ageRangeEn: "Ages 6 to 12",
    descriptionEl: "Περιορισμένα εργαλεία, πάντα με επίβλεψη ενήλικα.",
    descriptionEn: "Limited tools, always with adult supervision.",
  },
  {
    id: "middle",
    icon: "🎒",
    labelEl: "Γυμνάσιο",
    labelEn: "Middle School",
    ageRangeEl: "12 έως 15 ετών",
    ageRangeEn: "Ages 12 to 15",
    descriptionEl: "Περισσότερα εργαλεία, αρχή αυτόνομης χρήσης.",
    descriptionEn: "More tools, the start of independent use.",
  },
  {
    id: "high",
    icon: "🎓",
    labelEl: "Λύκειο",
    labelEn: "High School",
    ageRangeEl: "15 έως 18 ετών",
    ageRangeEn: "Ages 15 to 18",
    descriptionEl: "Σχεδόν πλήρες φάσμα εργαλείων, έμφαση στη σωστή χρήση.",
    descriptionEn: "Near full range of tools, emphasis on proper use.",
  },
];

// ---------- ΡΟΛΟΙ ("λεωφορεία") ----------
const ROLES = [
  {
    id: "guardian",
    icon: "👪",
    labelEl: "Γονιός / Εκπαιδευτικός",
    labelEn: "Parent / Educator",
    taglineEl: "Τι να ξέρεις, πώς να εποπτεύσεις",
    taglineEn: "What to know, how to supervise",
  },
  {
    id: "student",
    icon: "🧑‍🎓",
    labelEl: "Μαθητής",
    labelEn: "Student",
    taglineEl: "Πώς να το χρησιμοποιήσεις σωστά",
    taglineEn: "How to use it the right way",
  },
];

// ---------- ΚΑΤΗΓΟΡΙΕΣ ΕΡΓΑΛΕΙΩΝ ----------
const CATEGORIES = [
  { id: "writing", labelEl: "Γραφή & Κείμενο", labelEn: "Writing & Text" },
  { id: "research", labelEl: "Έρευνα & Μάθηση", labelEn: "Research & Learning" },
  { id: "math", labelEl: "Μαθηματικά & Λογική", labelEn: "Math & Logic" },
  { id: "creative", labelEl: "Δημιουργικότητα (εικόνα/ήχος)", labelEn: "Creative (image/audio)" },
  { id: "coding", labelEl: "Προγραμματισμός", labelEn: "Coding" },
  { id: "organization", labelEl: "Οργάνωση & Παραγωγικότητα", labelEn: "Organization & Productivity" },
  { id: "language", labelEl: "Γλώσσες", labelEn: "Languages" },
  // ΝΕΕΣ ΚΑΤΗΓΟΡΙΕΣ ΓΙΑ ΕΛΛΗΝΙΚΑ
  { id: "greek-edtech", labelEl: "🇬🇷 Ελληνική EdTech", labelEn: "🇬🇷 Greek EdTech" },
  { id: "greek-program", labelEl: "🇬🇷 Ελληνικό Πρόγραμμα", labelEn: "🇬🇷 Greek Program" },
];

/**
 * ---------- MASTER ΛΙΣΤΑ ΕΡΓΑΛΕΙΩΝ ----------
 */
const TOOLS = {
  // ---------- ΕΛΛΗΝΙΚΑ ΕΡΓΑΛΕΙΑ & ΠΡΟΓΡΑΜΜΑΤΑ ----------
  "chatgpt-edu": {
    id: "chatgpt-edu",
    name: "ChatGPT Edu (Πιλοτικό)",
    url: "https://openai.com/chatgpt/education",
    category: "greek-program",
    logo: null,
    minAge: 12,
    minAgeNote: "Πιλοτικό πρόγραμμα σε ελληνικά σχολεία από το 2026, μέσω σχολικού λογαριασμού — διαφορετικό προϊόν από το γενικό ChatGPT for Teens (13-17) που κυκλοφόρησε παγκοσμίως στις 18/8/2026. Το ChatGPT for Teens αφορά προσωπικούς λογαριασμούς εκτός σχολείου· δες το entry 'ChatGPT' για αυτό.",
    shortDescEl: "Πιλοτικό πρόγραμμα AI στα ελληνικά σχολεία. Εξατομικευμένη υποστήριξη σε όλα τα μαθήματα.",
    shortDescEn: "Pilot AI program in Greek schools. Personalized support across all subjects.",
    isGreek: true,
    greekSource: "Υπουργείο Παιδείας",
    linkTypeInfo: true,
    pending: true,
  },
  "magicschool": {
    id: "magicschool",
    name: "MagicSchool AI",
    url: "https://www.magicschool.ai",
    category: "greek-edtech",
    logo: null,
    minAge: 18,
    minAgeNote: "Εργαλείο για εκπαιδευτικούς, δωρεάν βασικό πλάνο.",
    shortDescEl: "Πλατφόρμα AI ειδικά σχεδιασμένη για εκπαιδευτικούς, με 80+ εργαλεία για σχέδια μαθήματος, αξιολόγηση και ανατροφοδότηση.",
    shortDescEn: "AI platform designed specifically for educators, with 80+ tools for lesson plans, assessment, and feedback.",
    isGreek: false,
  },
  "erla": {
    id: "erla",
    name: "Erla",
    url: "https://erla.app",
    category: "greek-edtech",
    logo: null,
    minAge: 10,
    minAgeNote: "Εφαρμογή εκμάθησης γλωσσών με AI, υποστηρίζει Ελληνικά. Διαθέσιμη ΜΟΝΟ ως εφαρμογή κινητού (App Store / Google Play) — δεν έχει χρηστική έκδοση web.",
    shortDescEl: "Εφαρμογή εκμάθησης γλωσσών με τη βοήθεια AI, μέσα από ακρόαση, ανάγνωση και συνομιλία. Υποστηρίζει Ελληνικά.",
    shortDescEn: "Language-learning app with AI assistance, through listening, reading, and conversation. Supports Greek.",
    isGreek: false,
    isMobileApp: true,
  },
  "autodraw": {
    id: "autodraw",
    name: "AutoDraw",
    url: "https://www.autodraw.com",
    category: "greek-edtech",
    logo: null,
    minAge: 6,
    minAgeNote: "Δωρεάν εργαλείο της Google. Καθόλου κείμενο απαιτούμενο, μόνο σχέδιο.",
    shortDescEl: "Ζωγραφίζεις με το ποντίκι ή το δάχτυλο και η ΤΝ μαντεύει τι σχεδιάζεις, προτείνοντας έτοιμα σχέδια. Χωρίς λογαριασμό, χωρίς κείμενο.",
    shortDescEn: "Draw with mouse or finger and the AI guesses what you're drawing, suggesting finished sketches. No account, no text needed.",
    isGreek: false,
  },
  "elements-of-ai": {
    id: "elements-of-ai",
    name: "Elements of AI (Ελληνικά)",
    url: "https://www.elementsofai.gr",
    category: "greek-program",
    logo: null,
    minAge: 15,
    minAgeNote: "Δωρεάν μάθημα AI προσβάσιμο στα ελληνικά.",
    shortDescEl: "Δωρεάν μάθημα για την τεχνητή νοημοσύνη, πλήρως μεταφρασμένο στα ελληνικά.",
    shortDescEn: "Free AI course, fully translated into Greek.",
    isGreek: true,
    greekSource: "AI HUB / ΕΕ",
  },

  "claude-academy": {
    id: "claude-academy",
    name: "Claude Academy",
    url: "https://academy.claude.com",
    category: "research",
    logo: null,
    minAge: 15,
    minAgeNote: "Δωρεάν, δεν χρειάζεται λογαριασμό για να διαβάσεις τα μαθήματα (μόνο για αποθήκευση προόδου). Το περιεχόμενο υποθέτει άνετη ανάγνωση αγγλικών.",
    shortDescEl: "Δωρεάν μαθήματα από την Anthropic για το πώς λειτουργεί πραγματικά το AI και πώς να συνεργάζεσαι μαζί του σωστά, υπεύθυνα και αποτελεσματικά (πλαίσιο 'AI Fluency': Ανάθεση, Περιγραφή, Κριτική Αξιολόγηση, Επιμέλεια).",
    shortDescEn: "Free courses from Anthropic on how AI actually works and how to collaborate with it responsibly and effectively (the 'AI Fluency' framework: Delegation, Description, Discernment, Diligence).",
    greekTips: "Το περιεχόμενο είναι μόνο στα αγγλικά, χωρίς επιλογή ελληνικών — κατάλληλο για μαθητές με άνεση στα αγγλικά, ή με τη βοήθεια εκπαιδευτικού.",
    isGreek: false,
  },

  // ---------- ΥΠΑΡΧΟΝΤΑ ΕΡΓΑΛΕΙΑ ----------
  "chatgpt": {
    id: "chatgpt",
    name: "ChatGPT",
    url: "https://chatgpt.com",
    category: "writing",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω. Από 18/8/2026, οι χρήστες 13-17 ετών μεταφέρονται αυτόματα στο ChatGPT for Teens (σταδιακό rollout, ολοκληρώνεται περίπου 2 εβδομάδες μετά). Περιλαμβάνει: αυστηρότερους περιορισμούς περιεχομένου (βία, επικίνδυνες προκλήσεις, ερωτικό/σεξουαλικό περιεχόμενο, αυτοτραυματισμό), 'Study Mode' (εξηγήσεις βήμα-βήμα αντί για έτοιμες απαντήσεις), quiz και οπτικοποιήσεις εξάσκησης, εντοπισμό προσπαθειών παράκαμψης εργασιών, και 'Study Hours' όπου ο μαθητής ή ένας συνδεδεμένος γονιός ορίζουν ώρες που το Study Mode ενεργοποιείται αυτόματα. Ο γονιός μπορεί να συνδέσει λογαριασμό και να διαχειριστεί ώρες ησυχίας, Voice Mode, δημιουργία εικόνων και Study Mode — όχι όμως να διαβάσει το περιεχόμενο των συνομιλιών. Ενεργοποιείται όταν ο χρήστης δηλώσει ηλικία 13-17, ή αν το σύστημα το εκτιμήσει (η εκτίμηση ηλικίας δεν είναι αλάνθαστη).",
    shortDescEl: "Γενικός chatbot AI για γραφή, εξηγήσεις και βοήθεια σε πολλά μαθήματα.",
    shortDescEn: "General purpose AI chatbot for writing, explanations, and help across subjects.",
    greekTips: "Ιδανικό για επεξήγηση αρχαίων κειμένων και νεοελληνικής λογοτεχνίας.",
  },
  "gemini": {
    id: "gemini",
    name: "Google Gemini",
    url: "https://gemini.google.com",
    category: "writing",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω για προσωπικό λογαριασμό. Κάτω των 13, μόνο μέσω Google Family Link. Από 10/8/2026, το Gemini μέσα στο Google Classroom άνοιξε σε μαθητές όλων των ηλικιών (και Δημοτικού) μέσω σχολικού λογαριασμού, αν το ενεργοποιήσει το σχολείο — flashcards, quiz εξάσκησης και οδηγοί μελέτης βασισμένα στο δικό τους υλικό, χωρίς να εκπαιδεύεται το μοντέλο πάνω στα δεδομένα τους. Ανεξάρτητες αξιολογήσεις (Common Sense Media) σημειώνουν ότι το γενικό Gemini (εκτός Classroom) δεν διαφοροποιεί επαρκώς τις απαντήσεις του ανάμεσα σε 13χρονο και 17χρονο χρήστη — μεγαλύτερη ανάγκη γονικής επίβλεψης σε σχέση με εργαλεία σχεδιασμένα ειδικά για παιδιά.",
    shortDescEl: "Chatbot AI της Google, ενσωματωμένο σε Google Classroom για μαθητές μέσω σχολείου.",
    shortDescEn: "Google's AI chatbot, integrated into Google Classroom for school managed student access.",
    greekTips: "Απαντάει κανονικά στα ελληνικά αν το ρωτήσεις στα ελληνικά. Η διεπαφή αλλάζει γλώσσα από τις ρυθμίσεις του λογαριασμού Google.",
  },
  "copilot": {
    id: "copilot",
    name: "Microsoft Copilot",
    url: "https://copilot.microsoft.com",
    category: "writing",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω (μπορεί να είναι υψηλότερο ανά χώρα). Χωρίς πρόσβαση κάτω του ορίου, ακόμη και με γονική άδεια.",
    shortDescEl: "AI βοηθός της Microsoft, ενσωματωμένος σε Word, Excel, PowerPoint και ως ανεξάρτητο chatbot.",
    shortDescEn: "Microsoft's AI assistant, built into Word, Excel, PowerPoint, and available as a standalone chatbot.",
  },
  "claude": {
    id: "claude",
    name: "Claude",
    url: "https://claude.ai",
    category: "writing",
    logo: null,
    minAge: 18,
    minAgeNote: "Μόνο 18 ετών και άνω. Δεν υπάρχει διαδρομή γονικής συγκατάθεσης για κάτω των 18.",
    shortDescEl: "AI chatbot της Anthropic. Δεν προσφέρει πρόσβαση σε ανηλίκους, ούτε με γονική άδεια.",
    shortDescEn: "Anthropic's AI chatbot. Offers no access path for minors, even with parental consent.",
    greekTips: "Απαντάει κανονικά στα ελληνικά αν του μιλήσεις ελληνικά, ακόμα κι αν κάποια κουμπιά της διεπαφής είναι στα αγγλικά.",
  },
  "grammarly": {
    id: "grammarly",
    name: "Grammarly",
    url: "https://www.grammarly.com",
    category: "writing",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω βάσει Όρων Χρήσης. Υπάρχει και εκπαιδευτική έκδοση (Grammarly for Education) για σχολικούς λογαριασμούς.",
    shortDescEl: "Εργαλείο διόρθωσης γραμματικής, ορθογραφίας και ύφους σε αγγλικό κείμενο.",
    shortDescEn: "Grammar, spelling, and style checking tool for English writing.",
    greekTips: "Ελέγχει μόνο αγγλικό κείμενο — δεν λειτουργεί για έλεγχο ελληνικών κειμένων.",
  },

  // ---------- ΕΡΕΥΝΑ & ΜΑΘΗΣΗ ----------
  "khanmigo": {
    id: "khanmigo",
    name: "Khanmigo (Khan Academy)",
    url: "https://www.khanacademy.org/khan-labs",
    category: "research",
    logo: null,
    minAge: 5,
    minAgeNote: "Σχεδιασμένο για μαθητές όλων των βαθμίδων. Κάτω των 13, ο λογαριασμός δημιουργείται και διαχειρίζεται από γονέα.",
    shortDescEl: "AI εκπαιδευτικός βοηθός πάνω στο Khan Academy. Καθοδηγεί με ερωτήσεις αντί να δίνει έτοιμη απάντηση.",
    shortDescEn: "AI tutor built on Khan Academy. Guides with Socratic questions instead of handing over answers.",
    greekTips: "Διαθέσιμο και στα ελληνικά. Εξαιρετικό για εξάσκηση στα Μαθηματικά Δημοτικού.",
  },
  "khan-academy-kids": {
    id: "khan-academy-kids",
    name: "Khan Academy Kids",
    url: "https://learn.khanacademy.org/khan-academy-kids/",
    category: "research",
    logo: null,
    minAge: 2,
    minAgeNote: "Σχεδιασμένο για ηλικίες 2-8. Εντελώς δωρεάν, χωρίς διαφημίσεις, χωρίς in-app αγορές, χωρίς συλλογή δεδομένων παιδιού (5 αστέρια στο Common Sense Media). Διαφέρει από το Khanmigo: δεν είναι AI chatbot/tutor, είναι βιβλιοθήκη διαδραστικών μαθημάτων/παιχνιδιών ανάγνωσης, μαθηματικών και κοινωνικο-συναισθηματικής μάθησης με προσαρμοστική δυσκολία.",
    shortDescEl: "Δωρεάν εφαρμογή για τις πιο μικρές ηλικίες (Νηπιαγωγείο, Α'-Β' Δημοτικού). Ανάγνωση, μαθηματικά και παιχνίδια με προσαρμοστική δυσκολία, χωρίς λογαριασμό να χρειάζεται για βασική χρήση.",
    shortDescEn: "Free app for the youngest ages (kindergarten, 1st-2nd grade). Reading, math, and games with adaptive difficulty, no account required for basic use.",
    greekTips: "Έχει επιλογή ελληνικής γλώσσας μέσα στην εφαρμογή (Ρυθμίσεις → Language) — βεβαιώσου ότι είναι ενεργοποιημένη πριν τη δώσεις στο παιδί.",
    isGreek: false,
  },
  "notebooklm": {
    id: "notebooklm",
    name: "Gemini Notebook (πρώην NotebookLM)",
    url: "https://notebook.google.com",
    category: "research",
    logo: null,
    minAge: 18,
    minAgeNote: "Απαιτεί προσωπικό λογαριασμό Google 18 ετών και άνω, ή σχολικό λογαριασμό Google Workspace for Education. Επιβεβαιωμένο: η Google μετονόμασε επίσημα το NotebookLM σε 'Gemini Notebook' στις 16/7/2026 — ίδιο εργαλείο, ίδιες πηγές/σημειώσεις, νέο URL (notebook.google.com, με αυτόματη ανακατεύθυνση από το παλιό). Δεν άλλαξε τίποτα στη λειτουργία ή στην πολιτική ηλικίας.",
    shortDescEl: "Εργαλείο της Google που συνοψίζει και οργανώνει σημειώσεις και πηγές που ανεβάζεις εσύ.",
    shortDescEn: "Google's tool that summarizes and organizes notes and sources you upload yourself.",
  },
  "perplexity": {
    id: "perplexity",
    name: "Perplexity",
    url: "https://www.perplexity.ai",
    category: "research",
    logo: null,
    minAge: 13,
    minAgeNote: "Διόρθωση: 13 ετών και άνω, όχι 18 (επιβεβαιωμένο απευθείας από τους επίσημους Όρους Χρήσης του Perplexity: 'Children under the age of 13 are not permitted to use the Services'). Δεν υπάρχει καμία διαδικασία ηλικιακής επαλήθευσης — βασίζεται αποκλειστικά στη δήλωση του χρήστη. Για 13-17, καλό είναι να υπάρχει γονική καθοδήγηση στην αξιολόγηση πηγών, αν και δεν αναφέρεται ρητά ξεχωριστή διαδικασία συγκατάθεσης γονέα στους Όρους.",
    shortDescEl: "Μηχανή έρευνας με AI που απαντά με βάση πηγές και παραθέτει τις πηγές του.",
    shortDescEn: "AI powered research and search engine that answers with cited sources.",
  },
  "wolfram-alpha": {
    id: "wolfram-alpha",
    name: "Wolfram Alpha",
    url: "https://www.wolframalpha.com",
    category: "math",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω βάσει Όρων Χρήσης. Χωρίς κοινωνικά χαρακτηριστικά ή chat ελεύθερης μορφής.",
    shortDescEl: "Υπολογιστική μηχανή γνώσης. Λύνει μαθηματικά, φυσική και χημεία βήμα βήμα.",
    shortDescEn: "Computational knowledge engine. Solves math, physics, and chemistry step by step.",
    greekTips: "Η διεπαφή και οι περισσότερες εξηγήσεις είναι μόνο στα αγγλικά, χωρίς επιλογή ελληνικών — πιο κατάλληλο για μεγαλύτερα παιδιά ή με τη βοήθεια ενήλικα δίπλα.",
  },
  "quizlet": {
    id: "quizlet",
    name: "Quizlet",
    url: "https://quizlet.com",
    category: "organization",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω βάσει Όρων Χρήσης. Οι εκπαιδευτικοί μπορούν να δημιουργήσουν λογαριασμούς τάξης για μικρότερους μαθητές. Προσοχή στο κόστος: οι AI λειτουργίες (Magic Notes — μετατροπή σημειώσεων σε flashcards/practice tests, Q-Chat — AI tutor) απαιτούν συνδρομή Quizlet Plus (περίπου 8€/μήνα ή 36€/έτος). Η δωρεάν έκδοση καλύπτει βασικά flashcards, Match και περιορισμένο Learn/Test.",
    shortDescEl: "Φλασκάρτες και quiz με AI υποβοηθούμενη δημιουργία για διάβασμα και απομνημόνευση.",
    shortDescEn: "Flashcards and quizzes with AI assisted creation for studying and memorization.",
  },

  // ---------- ΜΑΘΗΜΑΤΙΚΑ & ΛΟΓΙΚΗ ----------
  "photomath": {
    id: "photomath",
    name: "Photomath",
    url: "https://photomath.com",
    category: "math",
    logo: null,
    minAge: 4,
    minAgeNote: "Χωρίς αυστηρό όριο ηλικίας στους Όρους Χρήσης. Δεν έχει chat ελεύθερης μορφής ή κοινωνικά χαρακτηριστικά.",
    shortDescEl: "Φωτογραφίζεις ένα μαθηματικό πρόβλημα και σου δείχνει τη λύση βήμα βήμα.",
    shortDescEn: "Point your camera at a math problem and get a step by step solution.",
    greekTips: "Η λύση δείχνεται κυρίως με μαθηματικά σύμβολα και βήματα, όχι πολύ κείμενο — λειτουργεί καλά ακόμα κι αν το παιδί δεν διαβάζει άπταιστα αγγλικά. Κάποιες επεξηγήσεις παραμένουν στα αγγλικά.",
  },

  // ---------- ΔΗΜΙΟΥΡΓΙΚΟΤΗΤΑ ----------
  "canva-magic": {
    id: "canva-magic",
    name: "Canva (Magic Studio)",
    url: "https://www.canva.com",
    category: "creative",
    logo: null,
    minAge: 13,
    minAgeNote: "13 ετών και άνω για προσωπικό λογαριασμό. Υπάρχει Canva for Education με σχολικούς λογαριασμούς για μικρότερες ηλικίες υπό επίβλεψη εκπαιδευτικού.",
    shortDescEl: "Εργαλείο σχεδίασης με AI χαρακτηριστικά όπως δημιουργία εικόνων, αφαίρεση φόντου και κείμενο σε σχέδιο.",
    shortDescEn: "Design tool with AI features like image generation, background removal, and text to design.",
  },

  // ---------- ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ ----------
  "github-copilot": {
    id: "github-copilot",
    name: "GitHub Copilot",
    url: "https://github.com/features/copilot",
    category: "coding",
    logo: null,
    minAge: 13,
    minAgeNote: "Απαιτεί λογαριασμό GitHub (13 ετών και άνω). Δωρεάν έκδοση για επαληθευμένους μαθητές και φοιτητές μέσω GitHub Education.",
    shortDescEl: "AI βοηθός προγραμματισμού που προτείνει κώδικα μέσα στον επεξεργαστή κώδικα.",
    shortDescEn: "AI coding assistant that suggests code directly inside your code editor.",
  },

  // ---------- ΓΛΩΣΣΕΣ ----------
  "duolingo": {
    id: "duolingo",
    name: "Duolingo",
    url: "https://www.duolingo.com",
    category: "language",
    logo: null,
    minAge: 5,
    minAgeNote: "Δεν υπάρχει αυστηρό κατώτατο όριο. Κάτω των 13 ο λογαριασμός συνδέεται με email γονέα, με περιορισμένα κοινωνικά χαρακτηριστικά. Υπάρχει και ξεχωριστή εφαρμογή Duolingo Kids/ABC για μικρότερες ηλικίες.",
    shortDescEl: "Εκμάθηση γλωσσών με μικρά, παιχνιδοποιημένα μαθήματα. Οι νεότερες εκδόσεις χρησιμοποιούν AI για εξατομίκευση.",
    shortDescEn: "Language learning through short, gamified lessons. Newer features use AI for personalization.",
    greekTips: "Η εφαρμογή έχει ελληνική διεπαφή (μενού, κουμπιά) — άλλαξε τη γλώσσα εφαρμογής από τις ρυθμίσεις του λογαριασμού αν εμφανιστεί στα αγγλικά.",
  },
  "reading-coach": {
    id: "reading-coach",
    name: "Microsoft Reading Coach",
    url: "https://coach.microsoft.com",
    category: "language",
    logo: null,
    minAge: 6,
    minAgeNote: "Δωρεάν, χωρίς αυστηρό όριο ηλικίας στους Όρους Χρήσης — φτιαγμένο για μαθητές Δημοτικού και άνω. Σχεδιασμένο ειδικά για δυσλεξία και αναγνωστικές δυσκολίες, με ενσωματωμένο Immersive Reader. Το interface υποστηρίζει 81 γλώσσες, όμως χρειάζεται δικός σου έλεγχος αν η ελληνική γλώσσα καλύπτεται πλήρως στο reading coaching (ακρόαση/διόρθωση προφοράς) ή μόνο στο μενού πριν το προτείνεις ως εργαλείο ελληνικής ανάγνωσης.",
    shortDescEl: "Ακούει το παιδί να διαβάζει δυνατά και δίνει άμεση διόρθωση προφοράς και ρυθμού. Φτιαγμένο με έμφαση στην προσβασιμότητα.",
    shortDescEn: "Listens to a child read aloud and gives real-time pronunciation and fluency feedback. Built with accessibility in mind.",
  },

  // ---------- ΠΡΟΧΩΡΗΜΕΝΑ / ΕΞΕΙΔΙΚΕΥΜΕΝΑ ΕΡΓΑΛΕΙΑ ----------
  "symbolab": {
    id: "symbolab",
    name: "Symbolab",
    url: "https://www.symbolab.com",
    category: "math",
    logo: null,
    minAge: 13,
    minAgeNote: "Δωρεάν με περιορισμούς, επί πληρωμή για πλήρη βήματα.",
    shortDescEl: "Λύνει βήμα-βήμα εξισώσεις, ολοκληρώματα, παράγωγα, πίνακες.",
    shortDescEn: "Step-by-step solver for equations, integrals, derivatives, matrices.",
    isExpert: true,
  },
  "desmos": {
    id: "desmos",
    name: "Desmos",
    url: "https://www.desmos.com",
    category: "math",
    logo: null,
    minAge: 5,
    minAgeNote: "Δωρεάν, χωρίς όριο ηλικίας.",
    shortDescEl: "Διαδραστική γραφική απεικόνιση συναρτήσεων και δεδομένων.",
    shortDescEn: "Interactive graphing of functions and data.",
    isExpert: true,
  },
  "geogebra": {
    id: "geogebra",
    name: "GeoGebra",
    url: "https://www.geogebra.org",
    category: "math",
    logo: null,
    minAge: 6,
    minAgeNote: "Δωρεάν, χωρίς λογαριασμό απαιτούμενο για βασική χρήση. Συμμορφώνεται με COPPA.",
    shortDescEl: "Διαδραστική γεωμετρία, άλγεβρα και στατιστική στο ίδιο παράθυρο. Πολύ διαδεδομένο σε σχολεία.",
    shortDescEn: "Interactive geometry, algebra, and statistics in one window. Widely used in schools.",
    greekTips: "Έχει ελληνική διεπαφή — άλλαξε τη γλώσσα από το εικονίδιο ρυθμίσεων/globe στο μενού, στα Ελληνικά.",
    isExpert: true,
  },
  "scite": {
    id: "scite",
    name: "Scite",
    url: "https://scite.ai",
    category: "research",
    logo: null,
    minAge: 18,
    minAgeNote: "Ακαδημαϊκό εργαλείο, απαιτεί λογαριασμό.",
    shortDescEl: "Δείχνει αν μια επιστημονική αναφορά υποστηρίζει ή αντικρούει μια δήλωση.",
    shortDescEn: "Shows whether a scientific reference supports or contradicts a claim.",
    isExpert: true,
  },
  "elicit": {
    id: "elicit",
    name: "Elicit",
    url: "https://elicit.com",
    category: "research",
    logo: null,
    minAge: 18,
    minAgeNote: "Ακαδημαϊκό εργαλείο.",
    shortDescEl: "Βρίσκει ακαδημαϊκές εργασίες και εξάγει βασικά σημεία.",
    shortDescEn: "Finds academic papers and extracts key points.",
    isExpert: true,
  },
  "hemingway": {
    id: "hemingway",
    name: "Hemingway Editor",
    url: "https://hemingwayapp.com",
    category: "writing",
    logo: null,
    minAge: 5,
    minAgeNote: "Δωρεάν online έκδοση.",
    shortDescEl: "Διορθώνει βαριά σύνταξη, δείχνει δείκτη αναγνωσιμότητας.",
    shortDescEn: "Fixes heavy syntax, shows readability score.",
    greekTips: "Λειτουργεί μόνο σε αγγλικό κείμενο — δεν μπορεί να ελέγξει ή να βελτιώσει ελληνικό κείμενο.",
    isExpert: true,
  },
  "scribbr": {
    id: "scribbr",
    name: "Scribbr",
    url: "https://www.scribbr.com",
    category: "writing",
    logo: null,
    minAge: 13,
    minAgeNote: "Επί πληρωμή, με δωρεάν έλεγχο λογοκλοπής.",
    shortDescEl: "Έλεγχος λογοκλοπής και πρόταση βελτίωσης ύφους.",
    shortDescEn: "Plagiarism check and style improvement suggestions.",
    isExpert: true,
  },
  "replit-ai": {
    id: "replit-ai",
    name: "Replit AI",
    url: "https://replit.com",
    category: "coding",
    logo: null,
    minAge: 13,
    minAgeNote: "Δωρεάν για βασική χρήση.",
    shortDescEl: "Επεξεργαστής κώδικα με AI που τρέχει online, χωρίς εγκατάσταση.",
    shortDescEn: "Online code editor with AI, no installation needed.",
    isExpert: true,
  },
  "miro-ai": {
    id: "miro-ai",
    name: "Miro AI",
    url: "https://miro.com/ai",
    category: "organization",
    logo: null,
    minAge: 13,
    minAgeNote: "Δωρεάν με περιορισμούς.",
    shortDescEl: "Δημιουργία mind maps, διαγραμμάτων ροής με AI βοήθεια.",
    shortDescEn: "Mind maps, flowcharts with AI assistance.",
    isExpert: true,
  },
  "mindmup": {
    id: "mindmup",
    name: "MindMup",
    url: "https://www.mindmup.com",
    category: "organization",
    logo: null,
    minAge: 12,
    minAgeNote: "Δωρεάν, χωρίς λογαριασμό απαιτούμενο για βασική χρήση.",
    shortDescEl: "Απλοί εννοιολογικοί χάρτες, ιδανικοί για οργάνωση εργασιών ή διάρθρωση εργασίας πριν τη γραφή.",
    shortDescEn: "Simple concept maps, ideal for organizing assignments or structuring a project before writing.",
    greekTips: "Η διεπαφή είναι μόνο στα αγγλικά, χωρίς επιλογή ελληνικών, αλλά είναι κυρίως εικονίδια και σχήματα — το παιδί μπορεί να γράφει κανονικά ελληνικά μέσα στους κόμβους του χάρτη.",
    isExpert: true,
  },
};

/**
 * ---------- PATHS ----------
 */
const PATHS = {
  primary: {
    guardian: {
      introEl: "Σε αυτή την ηλικία, κάθε εργαλείο AI χρειάζεται δικό σου λογαριασμό, δική σου ρύθμιση ή άμεση παρουσία σου. Παρακάτω θα βρεις ποιο εργαλείο ταιριάζει σε ποια συγκεκριμένη σχολική δουλειά, και πώς αποκτά πρόσβαση το παιδί με τον σωστό τρόπο.",
      introEn: "At this age, every AI tool needs your account, your setup, or your direct presence. Below: which tool fits which specific schoolwork, and how the child gets access the right way.",
      tools: [
        {
          toolId: "autodraw",
          useCaseEl: "Ζωγραφική και δημιουργικές δραστηριότητες, χωρίς να χρειάζεται να ξέρει το παιδί να διαβάζει.",
          useCaseEn: "Drawing and creative activities, no reading required.",
          howToEl: "Δωρεάν, χωρίς λογαριασμό. Καθόλου κείμενο στην οθόνη, ιδανικό για μικρά παιδιά.",
          howToEn: "Free, no account needed. No text on screen, ideal for young children.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "khanmigo",
          useCaseEl: "Εξάσκηση μαθηματικών και ανάγνωσης με καθοδήγηση, όχι έτοιμες απαντήσεις.",
          useCaseEn: "Guided math and reading practice, not handed over answers.",
          howToEl: "Δημιούργησε εσύ τον λογαριασμό Khan Academy για το παιδί και σύνδεσέ τον με το σχολικό του πρόγραμμα.",
          howToEn: "Create the Khan Academy account yourself for the child and link it to their school curriculum.",
          cautionEl: "Επί πληρωμή, περίπου 44 δολάρια το έτος. Υπάρχει δωρεάν εκδοχή του Khan Academy χωρίς τον AI tutor.",
          cautionEn: "Paid, around $44 a year. A free Khan Academy version without the AI tutor also exists.",
        },
        {
          toolId: "photomath",
          useCaseEl: "Γρήγορος έλεγχος αν μια λύση μαθηματικού προβλήματος είναι σωστή.",
          useCaseEn: "Quick check of whether a math problem's solution is correct.",
          howToEl: "Χρησιμοποίησέ το ως εργαλείο ελέγχου μετά την προσπάθεια του παιδιού, όχι πριν.",
          howToEn: "Use it as a check after the child's own attempt, not before.",
          cautionEl: "Δεν έχει chat ή κοινωνικά χαρακτηριστικά, οπότε είναι ασφαλές από άποψη επικοινωνίας. Είναι όμως εύκολο να γίνει shortcut αντί για μάθηση.",
          cautionEn: "No chat or social features, so it is safe from a communication standpoint. It is easy to misuse as a shortcut instead of learning though.",
        },
        {
          toolId: "duolingo",
          useCaseEl: "Πρώτη επαφή με ξένη γλώσσα μέσα από σύντομα, παιχνιδοποιημένα μαθήματα.",
          useCaseEn: "First exposure to a foreign language through short, gamified lessons.",
          howToEl: "Δημιούργησε τον λογαριασμό με το δικό σου email. Έτσι ενεργοποιούνται αυτόματα τα παιδικά όρια.",
          howToEn: "Create the account with your own email. This automatically activates child safe limits.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "reading-coach",
          useCaseEl: "Εξάσκηση προφορικής ανάγνωσης και προφοράς, ιδιαίτερα χρήσιμο για παιδί με δυσκολίες στην ανάγνωση ή δυσλεξία.",
          useCaseEn: "Practicing reading aloud and pronunciation, especially useful for a child with reading difficulties or dyslexia.",
          howToEl: "Δωρεάν, στο coach.microsoft.com. Το παιδί διαβάζει δυνατά και το εργαλείο ακούει και διορθώνει.",
          howToEn: "Free, at coach.microsoft.com. The child reads aloud and the tool listens and corrects.",
          cautionEl: "Έλεγξε πρώτα αν η ελληνική γλώσσα υποστηρίζεται πλήρως για ανάγνωση (όχι μόνο για το μενού) πριν το προτείνεις για ελληνικό κείμενο.",
          cautionEn: "Check first whether Greek is fully supported for reading practice (not just the menu) before recommending it for Greek-language text.",
        },
        {
          toolId: "chatgpt",
          useCaseEl: "Εξήγηση μιας δύσκολης έννοιας με απλά λόγια πριν την εξηγήσεις εσύ στο παιδί, ή δημιουργία 5 σύντομων ερωτήσεων εξάσκησης πάνω σε ένα κεφάλαιο.",
          useCaseEn: "Explaining a tough concept in simple words before you explain it to the child, or creating 5 short practice questions on a chapter.",
          howToEl: "Γράψε π.χ. «Εξήγησέ μου την πρόσθεση κλασμάτων σαν να μιλάς σε 10χρονο» ή «Φτιάξε 5 ερωτήσεις πολλαπλής επιλογής πάνω σε αυτό το κεφάλαιο [επικόλλησε το κείμενο]».",
          howToEn: "Type e.g. 'Explain adding fractions like you're talking to a 10-year-old' or 'Make 5 multiple-choice questions on this chapter [paste the text]'.",
          cautionEl: "Λογαριασμός 13+ — το χρησιμοποιείς εσύ, όχι απευθείας το παιδί σε αυτή την ηλικία.",
          cautionEn: "13+ account — you use it yourself, not the child directly at this age.",
        },
        {
          toolId: "claude",
          useCaseEl: "Φτιάξιμο flashcards ή καρτελών επανάληψης από ένα κεφάλαιο του σχολικού βιβλίου, ή απλοποίηση ενός δύσκολου κειμένου στο επίπεδο του παιδιού.",
          useCaseEn: "Making flashcards or review cards from a textbook chapter, or simplifying a hard text to the child's level.",
          howToEl: "Επικόλλησε το κείμενο του μαθήματος και γράψε «Φτιάξε 10 flashcards ερώτηση-απάντηση για εξάσκηση» ή «Ξαναγράψε αυτό σε πιο απλή γλώσσα για μαθητή Δημοτικού».",
          howToEn: "Paste the lesson text and type 'Make 10 question-answer flashcards for practice' or 'Rewrite this in simpler language for a primary school student'.",
          cautionEl: "Λογαριασμός 18+ — μόνο για δική σου χρήση, όχι για το παιδί σε αυτή την ηλικία.",
          cautionEn: "18+ account — for your own use only, not for the child at this age.",
        },
        {
          toolId: "perplexity",
          useCaseEl: "Γρήγορη, τεκμηριωμένη απάντηση σε ερωτήσεις «γιατί» που κάνει το παιδί (π.χ. γιατί ο ουρανός είναι μπλε), με πηγές που μπορείς να διασταυρώσεις.",
          useCaseEn: "Quick, sourced answers to the 'why' questions kids ask (e.g. why is the sky blue), with sources you can double-check.",
          howToEl: "Ρώτα ό,τι σε ρώτησε το παιδί με τα δικά του λόγια, και δες τις πηγές κάτω από την απάντηση πριν του τη μεταφέρεις.",
          howToEn: "Ask whatever the child asked you, in their own words, and check the sources under the answer before you pass it on.",
          cautionEl: "Λογαριασμός 18+.",
          cautionEn: "18+ account.",
        },
        {
          toolId: "gemini",
          useCaseEl: "Σύνοψη ενός κεφαλαίου σε λίγες προτάσεις, ή ερωτήσεις επανάληψης βασισμένες σε φωτογραφία σελίδας από το σχολικό βιβλίο.",
          useCaseEn: "Summarizing a chapter in a few sentences, or review questions based on a photo of a textbook page.",
          howToEl: "Ανέβασε φωτογραφία της σελίδας και γράψε «Κάνε περίληψη σε 3 προτάσεις» ή «Φτιάξε 5 ερωτήσεις κατανόησης».",
          howToEn: "Upload a photo of the page and type 'Summarize in 3 sentences' or 'Make 5 comprehension questions'.",
          cautionEl: "Λογαριασμός 13+ για προσωπική χρήση, ή μέσω Google Classroom αν το προσφέρει το σχολείο.",
          cautionEn: "13+ account for personal use, or through Google Classroom if the school offers it.",
        },
        {
          toolId: "wolfram-alpha",
          useCaseEl: "Βήμα-βήμα λύση σε μαθηματικό πρόβλημα που δεν θυμάσαι πώς λύνεται, ώστε να το εξηγήσεις σωστά στο παιδί.",
          useCaseEn: "A step-by-step solution to a math problem you don't remember how to solve, so you can explain it correctly to the child.",
          howToEl: "Γράψε την άσκηση ακριβώς όπως είναι στο βιβλίο και δες την αναλυτική λύση βήμα-βήμα, πριν καθίσεις με το παιδί.",
          howToEn: "Type the exercise exactly as it appears in the book and see the step-by-step solution, before you sit down with the child.",
          cautionEl: "Λογαριασμός 13+. Δεν έχει chat ελεύθερης μορφής, οπότε είναι πιο περιορισμένο αλλά και πιο ασφαλές.",
          cautionEn: "13+ account. No free-form chat, so it's more limited but also safer.",
        },
        {
          toolId: "notebooklm",
          useCaseEl: "Οργάνωση φωτογραφιών από το τετράδιο ή το βιβλίο του παιδιού σε μία πηγή, και δημιουργία περίληψης ή quiz επανάληψης αποκλειστικά από αυτές.",
          useCaseEn: "Organizing photos from the child's notebook or textbook into one source, and creating a summary or review quiz from them alone.",
          howToEl: "Ανέβασε φωτογραφίες σελίδων ή σημειώσεων και ζήτα περίληψη ή ερωτήσεις επανάληψης βασισμένες αποκλειστικά σε αυτές, όχι σε εξωτερικές πηγές.",
          howToEn: "Upload photos of pages or notes and ask for a summary or review questions based only on them, not on outside sources.",
          cautionEl: "Λογαριασμός Google 18+, ή σχολικός λογαριασμός Google Workspace for Education.",
          cautionEn: "18+ Google account, or a school Google Workspace for Education account.",
        },
      ],
    },
    student: {
      introEl: "Αυτά τα εργαλεία τα χρησιμοποιείς πάντα με λογαριασμό που έφτιαξε ο γονιός ή ο δάσκαλός σου, όχι μόνος σου.",
      introEn: "You always use these tools through an account your parent or teacher set up, not on your own.",
      tools: [
        {
          toolId: "autodraw",
          useCaseEl: "Για να ζωγραφίσεις και να δεις πώς η ΤΝ μαντεύει τι σχεδιάζεις.",
          useCaseEn: "To draw and see how AI guesses what you're drawing.",
          howToEl: "Απλά ζωγράφισε. Δεν χρειάζεται να γράψεις τίποτα.",
          howToEn: "Just draw. No typing needed.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "khanmigo",
          useCaseEl: "Όταν κολλάς σε μαθηματικά ή ανάγνωση, σε βοηθάει με ερωτήσεις να βρεις μόνος σου τη λύση.",
          useCaseEn: "When you're stuck on math or reading, it helps you find the answer yourself through questions.",
          howToEl: "Προσπάθησε πρώτα μόνος σου, μετά ρώτα. Δεν σου δίνει την απάντηση αμέσως, και αυτό είναι καλό.",
          howToEn: "Try it yourself first, then ask. It won't just give you the answer right away, and that's a good thing.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "photomath",
          useCaseEl: "Για να δεις αν η άσκηση που έλυσες είναι σωστή.",
          useCaseEn: "To see if the exercise you solved is correct.",
          howToEl: "Λύσε πρώτα μόνος σου με το χέρι, μετά φωτογράφισε για να ελέγξεις.",
          howToEn: "Solve it yourself by hand first, then photograph it to check.",
          cautionEl: "Αν το χρησιμοποιείς πριν προσπαθήσεις, δεν μαθαίνεις. Απλά αντιγράφεις τη λύση.",
          cautionEn: "If you use it before trying, you're not learning. You're just copying the answer.",
        },
        {
          toolId: "duolingo",
          useCaseEl: "Για να μάθεις μια νέα γλώσσα με μικρά, διασκεδαστικά μαθήματα κάθε μέρα.",
          useCaseEn: "To learn a new language through short, fun daily lessons.",
          howToEl: "Κάνε λίγα λεπτά κάθε μέρα αντί για πολλή ώρα σπάνια. Έτσι θυμάσαι καλύτερα.",
          howToEn: "Do a few minutes every day instead of a lot rarely. That's how you remember better.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "reading-coach",
          useCaseEl: "Για να εξασκηθείς στην ανάγνωση δυνατά και να ακούσεις πώς προφέρεις σωστά τις λέξεις.",
          useCaseEn: "To practice reading aloud and hear how to pronounce words correctly.",
          howToEl: "Διάβασε δυνατά μπροστά στη συσκευή. Σε ακούει και σου λέει ποιες λέξεις να ξαναδοκιμάσεις.",
          howToEn: "Read aloud in front of the device. It listens and tells you which words to try again.",
          cautionEl: "",
          cautionEn: "",
        },
      ],
    },
  },

  middle: {
    guardian: {
      introEl: "Στα 13, ανοίγει η πρόσβαση στα περισσότερα mainstream AI chatbots, αλλά σχεδόν όλα απαιτούν τη δική σου συγκατάθεση μέχρι τα 17. Εδώ θα βρεις ποιο εργαλείο ταιριάζει σε ποια σχολική δουλειά, ώστε να καθοδηγήσεις τη χρήση αντί απλώς να την επιτρέψεις ή να την απαγορεύσεις.",
      introEn: "At 13, access opens up to most mainstream AI chatbots, but nearly all require your consent until age 17. Here's which tool fits which schoolwork, so you can guide the use rather than just allow or ban it.",
      tools: [
        {
          toolId: "erla",
          useCaseEl: "Ενίσχυση της ελληνικής γλώσσας, ορθογραφία και εκφραστικότητα.",
          useCaseEn: "Strengthening Greek language, spelling, and expression.",
          howToEl: "Ελληνικό εργαλείο. Κατάλληλο για μαθήματα Νεοελληνικής Γλώσσας.",
          howToEn: "Greek tool. Suitable for Modern Greek Language classes.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "chatgpt",
          useCaseEl: "Εξήγηση δύσκολων εννοιών με διαφορετικούς τρόπους, brainstorming για εργασίες.",
          useCaseEn: "Explaining tough concepts multiple ways, brainstorming for assignments.",
          howToEl: "Δώσε τη γονική συγκατάθεση μέσω των ρυθμίσεων λογαριασμού και ενεργοποίησε τους γονικούς ελέγχους σύνδεσης λογαριασμών.",
          howToEn: "Give parental consent through account settings and enable the parent teen account linking controls.",
          cautionEl: "Μπορεί να δώσει λανθασμένες πληροφορίες με σιγουριά. Χρειάζεται έλεγχος πηγών σε εργασίες.",
          cautionEn: "Can confidently give wrong information. Needs source checking for assignments.",
        },
        {
          toolId: "gemini",
          useCaseEl: "Βοήθεια σε έρευνα μαθήματος με εικόνες και κώδικα, μέσα σε ασφαλές πλαίσιο με φίλτρα περιεχομένου.",
          useCaseEn: "Help with subject research involving images and code, within a safety filtered environment.",
          howToEl: "Προτίμησε το αν το παιδί έχει ήδη λογαριασμό Google του σχολείου. Ενσωματώνεται φυσικά στο Classroom.",
          howToEn: "Prefer this if the child already has a school Google account. It integrates naturally with Classroom.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "wolfram-alpha",
          useCaseEl: "Επίλυση εξισώσεων και προβλημάτων φυσικής ή χημείας βήμα βήμα.",
          useCaseEn: "Solving equations and physics or chemistry problems step by step.",
          howToEl: "Καλή εναλλακτική στο Photomath για πιο σύνθετα προβλήματα Γυμνασίου.",
          howToEn: "A good alternative to Photomath for more complex middle school level problems.",
          cautionEl: "",
          cautionEn: "",
        },
      ],
    },
    student: {
      introEl: "Ξεκινάς να χρησιμοποιείς AI πιο μόνος σου, αλλά ο γονιός σου πρέπει να δώσει άδεια για τα περισσότερα chatbots. Δες ποιο εργαλείο ταιριάζει σε ποια δουλειά.",
      introEn: "You're starting to use AI more on your own, but your parent needs to give permission for most chatbots. See which tool fits which task.",
      tools: [
        {
          toolId: "erla",
          useCaseEl: "Για να βελτιώσεις τα ελληνικά σου και να γράφεις σωστά.",
          useCaseEn: "To improve your Greek and write correctly.",
          howToEl: "Χρησιμοποίησέ το για να ελέγχεις τις εκθέσεις σου.",
          howToEn: "Use it to check your essays.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "chatgpt",
          useCaseEl: "Για να σου εξηγήσει κάτι με άλλον τρόπο όταν δεν καταλαβαίνεις τον καθηγητή.",
          useCaseEn: "To explain something a different way when you don't understand your teacher.",
          howToEl: "Ζήτα εξήγηση, όχι έτοιμη απάντηση. Γράψε 'εξήγησέ μου γιατί', όχι 'δώσε μου τη λύση'.",
          howToEn: "Ask for an explanation, not a ready answer. Write 'explain why', not 'give me the solution'.",
          cautionEl: "Μπορεί να κάνει λάθη χωρίς να το καταλάβεις. Έλεγξε πάντα με το βιβλίο σου.",
          cautionEn: "It can make mistakes without you noticing. Always double check with your textbook.",
        },
        {
          toolId: "wolfram-alpha",
          useCaseEl: "Για να ελέγξεις μια άσκηση Άλγεβρας ή Φυσικής βήμα βήμα.",
          useCaseEn: "To check an Algebra or Physics problem step by step.",
          howToEl: "Προσπάθησε πρώτα μόνος σου με το χέρι, μετά έλεγξε.",
          howToEn: "Try it yourself by hand first, then check.",
          cautionEl: "",
          cautionEn: "",
        },
      ],
    },
  },

  high: {
    guardian: {
      introEl: "Στο Λύκειο το φάσμα εργαλείων είναι σχεδόν πλήρες, αλλά μερικά σοβαρά εργαλεία, όπως το Claude, το Perplexity και το NotebookLM, παραμένουν επίσημα 18 ετών και άνω χωρίς διαδρομή γονικής συγκατάθεσης. Η έμφαση μετατοπίζεται από τον περιορισμό στη σωστή, παραγωγική χρήση για προετοιμασία εξετάσεων, έρευνα και εργασίες.",
      introEn: "In high school the range of tools is nearly full, but a few serious tools, like Claude, Perplexity, and NotebookLM, remain officially 18 and up with no parental consent path. The focus shifts from restriction to proper, productive use for exam prep, research, and projects.",
      tools: [
        {
          toolId: "grammarly",
          useCaseEl: "Έλεγχος γραμματικής, ύφους και δομής σε εργασίες και έκθεση.",
          useCaseEn: "Grammar, style, and structure checking for assignments and essays.",
          howToEl: "Δωρεάν βασική έκδοση. Χρήσιμο ως δεύτερο μάτι μετά την πρώτη γραφή.",
          howToEn: "Free basic version. Useful as a second pair of eyes after the first draft.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "elements-of-ai",
          useCaseEl: "Εισαγωγή στην Τεχνητή Νοημοσύνη για μαθήματα Πληροφορικής.",
          useCaseEn: "Introduction to Artificial Intelligence for Computer Science classes.",
          howToEl: "Δωρεάν μάθημα στα ελληνικά. Κατάλληλο για εξωσχολική μελέτη.",
          howToEn: "Free course in Greek. Suitable for extracurricular study.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "claude-academy",
          useCaseEl: "Για να καταλάβεις εσύ πρώτος πώς λειτουργεί πραγματικά το AI, ώστε να καθοδηγήσεις σωστά το παιδί σου.",
          useCaseEn: "To understand yourself how AI really works, so you can properly guide your child.",
          howToEl: "Ξεκίνα από το 'AI Capabilities and Limitations' (3.5 ώρες) — δείχνει τι μπορεί και τι δεν μπορεί να κάνει αξιόπιστα ένα AI.",
          howToEn: "Start with 'AI Capabilities and Limitations' (3.5 hours) — it shows what AI can and can't reliably do.",
          cautionEl: "Μόνο στα αγγλικά.",
          cautionEn: "English only.",
        },
        {
          toolId: "chatgpt-edu",
          useCaseEl: "Πιλοτικό πρόγραμμα του Υπουργείου Παιδείας σε επιλεγμένα σχολεία.",
          useCaseEn: "Pilot program of the Ministry of Education in selected schools.",
          howToEl: "Ενημερώσου αν το σχολείο σου συμμετέχει στο πρόγραμμα.",
          howToEn: "Check if your school participates in the program.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "chatgpt",
          useCaseEl: "Οργάνωση διαβάσματος, εξηγήσεις σε πολλά μαθήματα, πρώτο draft εργασιών.",
          useCaseEn: "Study organization, explanations across subjects, first drafts of assignments.",
          howToEl: "Στα 15 έως 17 εξακολουθεί να χρειάζεται η γονική σου συγκατάθεση. Στα 18 όχι πια.",
          howToEn: "At 15 to 17 it still needs your parental consent. At 18 it no longer does.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "canva-magic",
          useCaseEl: "Παρουσιάσεις για σχολικές εργασίες και project, σχεδιασμός για μαθητικές δραστηριότητες.",
          useCaseEn: "Presentations for school projects, design for student activities.",
          howToEl: "Canva for Education δίνει δωρεάν πρόσβαση σε πολλά premium χαρακτηριστικά μέσω σχολικού λογαριασμού.",
          howToEn: "Canva for Education gives free access to many premium features via a school account.",
          cautionEl: "",
          cautionEn: "",
        },
      ],
    },
    student: {
      introEl: "Έχεις πρόσβαση σχεδόν στο πλήρες φάσμα εργαλείων. Το θέμα δεν είναι αν επιτρέπεται. Είναι ποιο εργαλείο ταιριάζει σε ποια δουλειά και πώς να το χρησιμοποιήσεις σωστά, ειδικά τώρα που ετοιμάζεσαι για εξετάσεις ή για σπουδές.",
      introEn: "You have access to nearly the full range of tools. The question isn't whether it's allowed. It's which tool fits which task and how to use it properly, especially now that you're preparing for exams or further studies.",
      tools: [
        {
          toolId: "grammarly",
          useCaseEl: "Για να γράψεις την έκθεση και τις εργασίες σου με σωστή δομή.",
          useCaseEn: "To write your essay and assignments with proper structure.",
          howToEl: "Χρησιμοποίησέ το μετά την πρώτη γραφή, για έλεγχο γλώσσας και δομής.",
          howToEn: "Use it after your first draft, to check language and structure.",
          cautionEl: "Μην αντιγράφεις έτοιμα κείμενα. Χρησιμοποίησέ το για δομή και ιδέες.",
          cautionEn: "Don't copy ready-made texts. Use it for structure and ideas.",
        },
        {
          toolId: "elements-of-ai",
          useCaseEl: "Για να μάθεις τα βασικά της Τεχνητής Νοημοσύνης.",
          useCaseEn: "To learn the basics of Artificial Intelligence.",
          howToEl: "Δωρεάν μάθημα. Μπορείς να το κάνεις παράλληλα με το σχολείο.",
          howToEn: "Free course. You can do it alongside school.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "claude-academy",
          useCaseEl: "Για να μάθεις πώς να συνεργάζεσαι σωστά με το AI αντί να το αφήνεις να σκέφτεται για σένα — χρήσιμο πριν αρχίσεις να το χρησιμοποιείς κανονικά για το σχολείο.",
          useCaseEn: "To learn how to properly collaborate with AI instead of letting it think for you — useful before you start using it regularly for school.",
          howToEl: "Το μάθημα 'AI Fluency: Framework & Foundations' (4 ώρες) διδάσκει πότε να εμπιστεύεσαι το AI και πότε όχι.",
          howToEn: "The 'AI Fluency: Framework & Foundations' course (4 hours) teaches when to trust AI and when not to.",
          cautionEl: "Μόνο στα αγγλικά.",
          cautionEn: "English only.",
        },
        {
          toolId: "chatgpt",
          useCaseEl: "Οργάνωση προγράμματος διαβάσματος, εξηγήσεις εννοιών από διαφορετική οπτική γωνία.",
          useCaseEn: "Organizing a study schedule, explaining concepts from a different angle.",
          howToEl: "Χρησιμοποίησέ το για να καταλάβεις, όχι για να αντιγράψεις. Στις εξετάσεις η ικανότητα να λύνεις μόνος σου είναι αυτό που μετράει.",
          howToEn: "Use it to understand, not to copy. For exams, your own problem solving ability is what counts.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "wolfram-alpha",
          useCaseEl: "Έλεγχος σύνθετων προβλημάτων Μαθηματικών ή Φυσικής Κατεύθυνσης.",
          useCaseEn: "Checking complex Math or Physics track problems.",
          howToEl: "Ιδανικό για επαλήθευση μετά την προσπάθειά σου, πριν το διαγώνισμα.",
          howToEn: "Ideal for verification after your own attempt, before the test.",
          cautionEl: "",
          cautionEn: "",
        },
        {
          toolId: "notebooklm",
          useCaseEl: "Σύνοψη κεφαλαίων, σημειώσεων ή πολλών πηγών σε οδηγό μελέτης πριν το διαγώνισμα.",
          useCaseEn: "Summarizing chapters, notes, or multiple sources into a study guide before a test.",
          howToEl: "Ανέβασε μόνο τις δικές σου σημειώσεις ή επιτρεπόμενες πηγές. Απαιτεί προσωπικό λογαριασμό Google 18 ετών και άνω, ή σχολικό λογαριασμό Google Workspace for Education.",
          howToEn: "Upload only your own notes or permitted sources. Requires a personal Google account aged 18+, or a school Google Workspace for Education account.",
          cautionEl: "Κάτω των 18 χωρίς σχολικό λογαριασμό δεν έχεις πρόσβαση. Έλεγξε πάντα τις παραπομπές πριν τις εμπιστευτείς.",
          cautionEn: "Under 18 without a school account, you won't have access. Always check citations before trusting them.",
        },
      ],
    },
  },
};

/**
 * ---------- PROMPTS ----------
 */
const PROMPTS = {
  primary: [
    {
      id: "primary-reading-summary",
      subjectEl: "Γλώσσα, Ανάγνωση",
      subjectEn: "Language, Reading",
      taskTypeEl: "Κατανόηση κειμένου",
      taskTypeEn: "Reading comprehension",
      promptTextEl: "Διάβασα αυτό το κείμενο και νομίζω ότι μιλάει για [γράψε με δικά σου λόγια τι κατάλαβες, έστω και λίγες προτάσεις]. Ρώτησέ με μία ερώτηση για να δεις αν το κατάλαβα σωστά. Μην μου πεις εσύ την περίληψη.",
      promptTextEn: "I read this text and I think it's about [write in your own words what you understood, even a couple of sentences]. Ask me one question to check if I understood it correctly. Don't tell me the summary yourself.",
      tipEl: "Γράψε πρώτα ό,τι θυμάσαι, χωρίς να ξαναδιαβάσεις. Μετά ρώτα.",
      tipEn: "Write down what you remember first, without rereading. Then ask.",
    },
    {
      id: "primary-math-check",
      subjectEl: "Μαθηματικά",
      subjectEn: "Math",
      taskTypeEl: "Έλεγχος άσκησης",
      taskTypeEn: "Checking an exercise",
      promptTextEl: "Έλυσα αυτή την άσκηση και βρήκα ότι [γράψε τη λύση σου]. Πες μου μόνο αν είναι σωστό ή λάθος. Αν είναι λάθος, μη μου δώσεις τη σωστή λύση, ρώτησέ με πού νομίζεις ότι έκανα λάθος.",
      promptTextEn: "I solved this exercise and got [write your solution]. Just tell me if it's right or wrong. If it's wrong, don't give me the correct solution, ask me where I think I made the mistake.",
      tipEl: "Λύσε πρώτα μόνος σου με το χέρι, μετά έλεγξε.",
      tipEn: "Solve it yourself by hand first, then check.",
    },
    {
      id: "primary-greek-myth",
      subjectEl: "Ιστορία, Μυθολογία",
      subjectEn: "History, Mythology",
      taskTypeEl: "Δημιουργική γραφή",
      taskTypeEn: "Creative writing",
      promptTextEl: "Θέλω να γράψω μια ιστορία για τον [γράψε έναν ήρωα της ελληνικής μυθολογίας, π.χ. Θησέα]. Νομίζω ότι ο ήρωας είχε αυτές τις ιδιότητες: [γράψε 2-3 χαρακτηριστικά]. Βοήθησέ με να σκεφτώ μια περιπέτεια που να ταιριάζει σε αυτόν τον ήρωα. Μη γράψεις εσύ την ιστορία.",
      promptTextEn: "I want to write a story about [write a Greek mythology hero, e.g. Theseus]. I think the hero had these qualities: [write 2-3 characteristics]. Help me think of an adventure that fits this hero. Don't write the story yourself.",
      tipEl: "Σκέψου τι έκανε τον ήρωα ξεχωριστό και ξεκίνα από εκεί.",
      tipEn: "Think about what made the hero special and start from there.",
    },
    {
      id: "primary-game-learning",
      subjectEl: "Οποιοδήποτε μάθημα",
      subjectEn: "Any subject",
      taskTypeEl: "Παιχνίδι κατανόησης",
      taskTypeEn: "Understanding game",
      promptTextEl: "Δυσκολεύομαι να καταλάβω [γράψε το θέμα, π.χ. τον κύκλο του νερού]. Ξέρω μέχρι στιγμής ότι [γράψε ό,τι θυμάσαι, έστω λίγο]. Φτιάξε μου ένα μικρό παιχνίδι ερωτήσεων για να το μάθω παίζοντας, μία ερώτηση τη φορά.",
      promptTextEn: "I'm having trouble understanding [write the topic, e.g. the water cycle]. So far I know that [write what you remember, even a little]. Make me a small question game to learn it by playing, one question at a time.",
      tipEl: "Πες πρώτα τι ήδη ξέρεις, ακόμα κι αν είναι λίγο ή λάθος.",
      tipEn: "Say what you already know first, even if it's little or wrong.",
    },
  ],
  middle: [
    {
      id: "middle-essay-structure",
      subjectEl: "Νεοελληνική Γλώσσα",
      subjectEn: "Modern Greek Language",
      taskTypeEl: "Έκθεση",
      taskTypeEn: "Essay",
      promptTextEl: "Γράφω έκθεση με θέμα [γράψε το θέμα σου]. Η δική μου θέση είναι ότι [γράψε με λίγα λόγια τι πιστεύεις εσύ πάνω στο θέμα]. Κάνε μου 3 ερωτήσεις που θα με βοηθήσουν να αναπτύξω αυτή τη θέση με δικά μου επιχειρήματα. Μη γράψεις εσύ την έκθεση ή παραγράφους έτοιμες προς χρήση.",
      promptTextEn: "I'm writing an essay on [write your topic]. My own position is that [write in a few words what you think about it]. Ask me 3 questions that will help me develop this position with my own arguments. Don't write the essay yourself or ready to use paragraphs.",
      tipEl: "Ξεκίνα πάντα από τη δική σου θέση, ακόμα κι αν δεν είσαι σίγουρος.",
      tipEn: "Always start from your own position, even if you're not sure.",
    },
    {
      id: "middle-history-presentation",
      subjectEl: "Ιστορία",
      subjectEn: "History",
      taskTypeEl: "Παρουσίαση",
      taskTypeEn: "Presentation",
      promptTextEl: "Κάνω παρουσίαση για την Ελληνική Επανάσταση του 1821. Έχω ήδη σκεφτεί αυτά τα σημεία: [γράψε 2 με 3 πράγματα που ήδη ξέρεις ή θυμάσαι]. Ρώτησέ με τι άλλο νομίζω ότι χρειάζεται η παρουσίαση, χωρίς να μου δώσεις εσύ τα υπόλοιπα σημεία.",
      promptTextEn: "I'm making a presentation about the Greek Revolution of 1821. I've already thought of these points: [write 2 to 3 things you already know or remember]. Ask me what else I think the presentation needs, without giving me the remaining points yourself.",
      tipEl: "Φτιάξε πρώτα τη δική σου λίστα σημείων, όσο μικρή κι αν είναι.",
      tipEn: "Make your own list of points first, however small.",
    },
    {
      id: "middle-science-explain",
      subjectEl: "Φυσική, Χημεία",
      subjectEn: "Physics, Chemistry",
      taskTypeEl: "Κατανόηση έννοιας",
      taskTypeEn: "Understanding a concept",
      promptTextEl: "Δεν καταλαβαίνω καλά την έννοια [γράψε την έννοια, π.χ. πυκνότητα, ταχύτητα]. Νομίζω ότι σημαίνει [γράψε τη δική σου εξήγηση, έστω κι αν δεν είσαι σίγουρος]. Πες μου τι απ' αυτά είναι σωστό και τι όχι, και εξήγησέ μου με ένα παράδειγμα από την καθημερινή ζωή.",
      promptTextEn: "I don't fully understand the concept of [write the concept, e.g. density, speed]. I think it means [write your own explanation, even if you're not sure]. Tell me what's right and what's not, and explain it with an everyday example.",
      tipEl: "Δοκίμασε πρώτα να το εξηγήσεις με δικά σου λόγια, ακόμα κι αν κάνεις λάθος.",
      tipEn: "Try to explain it in your own words first, even if you get it wrong.",
    },
    {
      id: "middle-greek-poetry",
      subjectEl: "Νεοελληνική Λογοτεχνία",
      subjectEn: "Modern Greek Literature",
      taskTypeEl: "Ανάλυση ποιήματος",
      taskTypeEn: "Poem analysis",
      promptTextEl: "Διαβάζω το ποίημα '[γράψε τίτλο ποιήματος, π.χ. του Σεφέρη ή Ελύτη]' και νομίζω ότι ο ποιητής μιλάει για [γράψε τη δική σου ερμηνεία σε 2 προτάσεις]. Κάνε μου 2 ερωτήσεις που θα με βοηθήσουν να σκεφτώ βαθύτερα το νόημα, χωρίς να μου δώσεις εσύ την ερμηνεία.",
      promptTextEn: "I'm reading the poem '[write poem title, e.g. by Seferis or Elytis]' and I think the poet is talking about [write your interpretation in 2 sentences]. Ask me 2 questions that will help me think deeper about the meaning, without giving me the interpretation yourself.",
      tipEl: "Διάβασε το ποίημα 2 φορές πριν γράψεις τη σκέψη σου.",
      tipEn: "Read the poem twice before writing your thought.",
    },
    {
      id: "middle-interview-style",
      subjectEl: "Οποιοδήποτε μάθημα",
      subjectEn: "Any subject",
      taskTypeEl: "Κατανόηση μέσα από ερωτήσεις",
      taskTypeEn: "Understanding through questions",
      promptTextEl: "Θα σου εξηγήσω ό,τι κατάλαβα από το μάθημα για [γράψε το θέμα, π.χ. το κυκλοφορικό σύστημα]. Εσύ ρώτησέ με ανοιχτές ερωτήσεις, μία-μία, σαν να είσαι συμμαθητής μου που θέλει να καταλάβει. Μη μου κάνεις διάλεξη και μη μου λες έτοιμα γεγονότα, εκτός αν σου ζητήσω διευκρίνιση.",
      promptTextEn: "I'll explain what I understood from class about [write the topic, e.g. the circulatory system]. You ask me open-ended questions, one at a time, like a classmate who wants to understand. Don't lecture me or list ready facts unless I ask for clarification.",
      tipEl: "Εξήγησε πρώτα με δικά σου λόγια, ακόμα κι αν δεν είσαι σίγουρος για όλα.",
      tipEn: "Explain it in your own words first, even if you're not sure about everything.",
    },
    {
      id: "middle-spot-errors",
      subjectEl: "Ξένη Γλώσσα",
      subjectEn: "Foreign Language",
      taskTypeEl: "Εντοπισμός λαθών",
      taskTypeEn: "Spotting errors",
      promptTextEl: "Μαθαίνω [γράψε τη γλώσσα, π.χ. Αγγλικά] σε επίπεδο [γράψε το επίπεδό σου]. Γράψε μου προτάσεις με μικρά γραμματικά λάθη στη γλώσσα αυτή, και εγώ θα προσπαθήσω να τα εντοπίσω και να τα διορθώσω. Μη μου λες τη διόρθωση αμέσως, περίμενε την απάντησή μου πρώτα.",
      promptTextEn: "I'm learning [write the language] at [write your level]. Write me sentences with small grammar mistakes in that language, and I'll try to spot and fix them. Don't tell me the correction right away, wait for my answer first.",
      tipEl: "Ζήτα προτάσεις σχετικές με λάθη που κάνεις συχνά εσύ.",
      tipEn: "Ask for sentences related to mistakes you commonly make yourself.",
    },
  ],
  high: [
    {
      id: "high-essay-argument",
      subjectEl: "Νεοελληνική Γλώσσα, Έκθεση",
      subjectEn: "Modern Greek Language, Essay",
      taskTypeEl: "Ανάπτυξη επιχειρήματος",
      taskTypeEn: "Developing an argument",
      promptTextEl: "Γράφω έκθεση με θέμα [γράψε το θέμα]. Το επιχείρημά μου είναι [γράψε το επιχείρημά σου με 2 με 3 προτάσεις]. Βρες αδυναμίες ή κενά στη σκέψη μου και κάνε μου ερωτήσεις που θα με βάλουν να το σκεφτώ καλύτερα. Μη γράψεις εσύ βελτιωμένη εκδοχή του επιχειρήματος.",
      promptTextEn: "I'm writing an essay on [write the topic]. My argument is [write your argument in 2 to 3 sentences]. Find weaknesses or gaps in my reasoning and ask me questions that will make me think it through better. Don't write an improved version of the argument yourself.",
      tipEl: "Όσο πιο ατελές είναι το πρώτο σου επιχείρημα, τόσο πιο χρήσιμη γίνεται η συζήτηση.",
      tipEn: "The more imperfect your first argument is, the more useful the discussion becomes.",
    },
    {
      id: "high-math-proof",
      subjectEl: "Μαθηματικά",
      subjectEn: "Math",
      taskTypeEl: "Μαθηματική απόδειξη",
      taskTypeEn: "Mathematical proof",
      promptTextEl: "Προσπαθώ να αποδείξω ότι [γράψε τι θέλεις να αποδείξεις]. Μέχρι τώρα έχω σκεφτεί αυτά τα βήματα: [γράψε ό,τι έχεις μέχρι στιγμής, ακόμα κι αν είναι ημιτελές]. Πες μου αν το βήμα που κόλλησα είναι σωστή κατεύθυνση, χωρίς να μου δώσεις το επόμενο βήμα της απόδειξης.",
      promptTextEn: "I'm trying to prove that [write what you want to prove]. So far I've thought of these steps: [write what you have so far, even if incomplete]. Tell me if the step where I'm stuck is the right direction, without giving me the next step of the proof.",
      tipEl: "Γράψε ακριβώς πού κόλλησες, όχι μόνο το τελικό αποτέλεσμα που θέλεις.",
      tipEn: "Write exactly where you got stuck, not just the final result you want.",
    },
    {
      id: "high-research-topic",
      subjectEl: "Ερευνητική Εργασία",
      subjectEn: "Research Project",
      taskTypeEl: "Διαμόρφωση ερευνητικού ερωτήματος",
      taskTypeEn: "Forming a research question",
      promptTextEl: "Θέλω να κάνω ερευνητική εργασία πάνω στην αρχαία ελληνική τεχνολογία. Το ερώτημα που με ενδιαφέρει είναι [γράψε το δικό σου ερώτημα, όσο ασαφές κι αν είναι ακόμα]. Βοήθησέ με να το κάνω πιο συγκεκριμένο με ερωτήσεις, χωρίς να μου προτείνεις εσύ το τελικό ερευνητικό ερώτημα.",
      promptTextEn: "I want to do a research project on ancient Greek technology. The question I'm interested in is [write your own question, however unclear it still is]. Help me make it more specific through questions, without suggesting the final research question yourself.",
      tipEl: "Ένα ασαφές ερώτημα δικό σου είναι καλύτερη αφετηρία από ένα έτοιμο ερώτημα του AI.",
      tipEn: "A vague question of your own is a better starting point than a ready made question from AI.",
    },
    {
      id: "high-panhellenic-essay",
      subjectEl: "Νεοελληνική Γλώσσα (Πανελλήνιες)",
      subjectEn: "Modern Greek Language (Panhellenic Exams)",
      taskTypeEl: "Δομή έκθεσης",
      taskTypeEn: "Essay structure",
      promptTextEl: "Ετοιμάζομαι για τις Πανελλήνιες και εξασκούμαι σε έκθεση με θέμα: '[γράψε το θέμα]'. Η δική μου θέση είναι: [γράψε τη θέση σου σε 2 προτάσεις]. Τα 3 επιχειρήματά μου είναι: [γράψε τα 3 επιχειρήματά σου]. Βρες αδυναμίες στη δομή μου και κάνε μου ερωτήσεις που θα με βοηθήσουν να τα αναπτύξω καλύτερα. Μη γράψεις εσύ βελτιωμένη εκδοχή.",
      promptTextEn: "I'm preparing for Panhellenic exams and practicing an essay on: '[write the topic]'. My position is: [write your position in 2 sentences]. My 3 arguments are: [write your 3 arguments]. Find weaknesses in my structure and ask me questions that will help me develop them better. Don't write an improved version yourself.",
      tipEl: "Ξεκίνα με ένα ισχυρό εισαγωγικό επιχείρημα.",
      tipEn: "Start with a strong introductory argument.",
    },
    {
      id: "high-pregrade-check",
      subjectEl: "Οποιοδήποτε μάθημα",
      subjectEn: "Any subject",
      taskTypeEl: "Αυτοέλεγχος πριν την παράδοση",
      taskTypeEn: "Self-check before submission",
      promptTextEl: "Έγραψα αυτή την εργασία και θέλω να την ελέγξω πριν την παραδώσω: [επικόλλησε το κείμενό σου ή περιέγραψέ το]. Τα κριτήρια αξιολόγησης είναι: [γράψε τα κριτήρια αν τα έχεις, αλλιώς πες τι νομίζεις ότι θα εκτιμήσει ο καθηγητής]. Βαθμολόγησέ την σαν να ήσουν ο καθηγητής μου, και πες μου τα 2 πιο σημαντικά σημεία που πρέπει να βελτιώσω. Μη μου ξαναγράψεις εσύ την εργασία.",
      promptTextEn: "I wrote this assignment and want to check it before submitting: [paste your text or describe it]. The grading criteria are: [write the criteria if you have them, or what you think the teacher will value]. Grade it as if you were my teacher, and tell me the 2 most important points I should improve. Don't rewrite the assignment for me.",
      tipEl: "Χρησιμοποίησέ το ως τελευταίο βήμα, όχι ως υποκατάστατο του να γράψεις εσύ.",
      tipEn: "Use it as a final step, not as a substitute for writing it yourself.",
    },
    {
      id: "high-learn-analogy",
      subjectEl: "Φυσική, Βιολογία, Οικονομικά",
      subjectEn: "Physics, Biology, Economics",
      taskTypeEl: "Κατανόηση με αναλογία",
      taskTypeEn: "Understanding through analogy",
      promptTextEl: "Θέλω να καταλάβω καλύτερα την έννοια [γράψε την έννοια, π.χ. εντροπία, προσφορά και ζήτηση]. Μέχρι τώρα το καταλαβαίνω έτσι: [γράψε τη δική σου κατανόηση, ακόμα κι αν είναι ασαφής]. Εξήγησέ μου την με μια αναλογία από την καθημερινή ζωή, και μετά ρώτησέ με αν η αναλογία μου βγάζει νόημα.",
      promptTextEn: "I want to better understand the concept of [write the concept, e.g. entropy, supply and demand]. So far I understand it like this: [write your own understanding, even if vague]. Explain it to me with an everyday-life analogy, then ask me if the analogy makes sense to me.",
      tipEl: "Μια αναλογία δικιά σου, ακόμα κι αν είναι ατελής, βοηθάει περισσότερο από μια έτοιμη εξήγηση.",
      tipEn: "Your own analogy, even if imperfect, helps more than a ready made explanation.",
    },
  ],
};
