// ---------- ΠΡΟΧΩΡΗΜΕΝΑ / ΕΞΕΙΔΙΚΕΥΜΕΝΑ ΕΡΓΑΛΕΙΑ ----------
"symbolab": {
  id: "symbolab",
  name: "Symbolab",
  url: "https://www.symbolab.com",
  category: "math",
  logo: null,
  minAge: 13,
  minAgeNote: "Δωρεάν με περιορισμούς, επί πληρωμή για πλήρη βήματα.",
  shortDescEl: "Λύνει βήμα-βήμα εξισώσεις, ολοκληρώματα, παράγωγα, πίνακες.",
  shortDescEn: "Step-by-step solver for equations, integrals, derivatives, matrices.",
  isExpert: true,
},
"desmos": {
  id: "desmos",
  name: "Desmos",
  url: "https://www.desmos.com",
  category: "math",
  logo: null,
  minAge: 5,
  minAgeNote: "Δωρεάν, χωρίς όριο ηλικίας.",
  shortDescEl: "Διαδραστική γραφική απεικόνιση συναρτήσεων και δεδομένων.",
  shortDescEn: "Interactive graphing of functions and data.",
  isExpert: true,
},
"scite": {
  id: "scite",
  name: "Scite",
  url: "https://scite.ai",
  category: "research",
  logo: null,
  minAge: 18,
  minAgeNote: "Ακαδημαϊκό εργαλείο, απαιτεί λογαριασμό.",
  shortDescEl: "Δείχνει αν μια επιστημονική αναφορά υποστηρίζει ή αντικρούει μια δήλωση.",
  shortDescEn: "Shows whether a scientific reference supports or contradicts a claim.",
  isExpert: true,
},
"elicit": {
  id: "elicit",
  name: "Elicit",
  url: "https://elicit.org",
  category: "research",
  logo: null,
  minAge: 18,
  minAgeNote: "Ακαδημαϊκό εργαλείο.",
  shortDescEl: "Βρίσκει ακαδημαϊκές εργασίες και εξάγει βασικά σημεία.",
  shortDescEn: "Finds academic papers and extracts key points.",
  isExpert: true,
},
"hemingway": {
  id: "hemingway",
  name: "Hemingway Editor",
  url: "https://hemingwayapp.com",
  category: "writing",
  logo: null,
  minAge: 5,
  minAgeNote: "Δωρεάν online έκδοση.",
  shortDescEl: "Διορθώνει βαριά σύνταξη, δείχνει δείκτη αναγνωσιμότητας.",
  shortDescEn: "Fixes heavy syntax, shows readability score.",
  isExpert: true,
},
"scribbr": {
  id: "scribbr",
  name: "Scribbr",
  url: "https://www.scribbr.com",
  category: "writing",
  logo: null,
  minAge: 13,
  minAgeNote: "Επί πληρωμή, με δωρεάν έλεγχο λογοκλοπής.",
  shortDescEl: "Έλεγχος λογοκλοπής και πρόταση βελτίωσης ύφους.",
  shortDescEn: "Plagiarism check and style improvement suggestions.",
  isExpert: true,
},
"replit-ai": {
  id: "replit-ai",
  name: "Replit AI",
  url: "https://replit.com",
  category: "coding",
  logo: null,
  minAge: 13,
  minAgeNote: "Δωρεάν για βασική χρήση.",
  shortDescEl: "Επεξεργαστής κώδικα με AI που τρέχει online, χωρίς εγκατάσταση.",
  shortDescEn: "Online code editor with AI, no installation needed.",
  isExpert: true,
},
"miro-ai": {
  id: "miro-ai",
  name: "Miro AI",
  url: "https://miro.com/ai",
  category: "organization",
  logo: null,
  minAge: 13,
  minAgeNote: "Δωρεάν με περιορισμούς.",
  shortDescEl: "Δημιουργία mind maps, διαγραμμάτων ροής με AI βοήθεια.",
  shortDescEn: "Mind maps, flowcharts with AI assistance.",
  isExpert: true,
},
