(()=>{"use strict";
const $=i=>document.getElementById(i),K="aitools4kids-language-v1",P={x:.18,y:.72},keys=new Set();let dir=null,last=performance.now(),run=0,near=0,words=[];
const base=()=>{try{return JSON.parse(localStorage.getItem("aitools4kids-play-v3")||localStorage.getItem("aitools4kids-play-v2")||"{}")}catch{return {}}},hist=()=>!!base().done?.history,done=()=>localStorage.getItem(K)==="done";
const st=document.createElement("style");st.textContent=".lang-status{position:absolute;z-index:9;left:56%;top:calc(76% + 48px);transform:translateX(-50%);padding:7px 10px;border-radius:10px;background:#18364de8;color:#fff;font:800 10px system-ui;text-align:center;pointer-events:none}.lang-status.ready{background:#6d37aae8;box-shadow:0 0 20px #8c4ed188}.lang-pill{background:#f1e9ff;color:#6d37aa}.lang-final{position:absolute;z-index:70;inset:0;display:grid;place-items:center;padding:25px;background:#092b49e8}.lang-final>div{width:min(560px,100%);padding:30px;border-radius:26px;background:#fff;text-align:center}.lang-final h1{font-size:clamp(34px,6vw,54px);margin:.2em 0}.lang-final .trophy{font-size:70px}.word-chip:disabled{opacity:.42}";document.head.appendChild(st);
const s=document.createElement("div");s.id="langStatus";s.className="lang-status";$("world").appendChild(s);
const m=document.createElement("section");m.id="langModal";m.className="modal";m.hidden=1;m.innerHTML=`<div class="card quiz"><button id="langClose" class="close">×</button><div class="top"><span class="pill lang-pill">📚 Language Academy</span><b id="langCount">1/3</b></div><h2 id="langTitle">Η βιβλιοθήκη των λέξεων</h2><div id="langIntro"><p class="q">Οι λέξεις έφυγαν από τις σελίδες. Βοήθησέ με να ξαναφτιάξουμε μια σωστή πρόταση.</p><button id="langStart" class="btn primary">Ξεκινάω</button></div><div id="langSentence" class="sortbox" hidden><p class="q">Πάτησε τις λέξεις με τη σωστή σειρά.</p><div class="sortcards"><button class="sortcard word-chip" data-w="διαβάζει">διαβάζει</button><button class="sortcard word-chip" data-w="Το">Το</button><button class="sortcard word-chip" data-w="βιβλίο.">βιβλίο.</button><button class="sortcard word-chip" data-w="ένα">ένα</button><button class="sortcard word-chip" data-w="παιδί">παιδί</button></div><div id="langSeq" class="sequence"></div><div id="langFb" class="feedback" hidden><div>✍️</div><div><h3 id="langFt"></h3><p id="langFp"></p></div></div><div class="actions"><button id="langReset" class="btn soft" hidden>Ξανά</button><button id="langNext" class="btn primary" hidden>Επόμενο</button></div></div><div id="langVerb" hidden><p class="q">Στην πρόταση «Η Μαρία γράφει μια ιστορία.», ποια λέξη είναι το ρήμα;</p><div class="materials"><button data-v="m">Μαρία</button><button data-v="g">γράφει</button><button data-v="i">ιστορία</button></div><div id="verbFb" class="feedback" hidden><div>📖</div><div><h3 id="verbFt"></h3><p id="verbFp"></p></div></div><div class="actions"><button id="langFinish" class="btn primary" hidden>Ολοκλήρωση κόσμου</button></div></div></div>`;document.body.insertBefore(m,$("finish"));
function sync(){let h=hist(),d=done();s.textContent=d?"✓ Ολοκληρώθηκε":h?(near?"📚 Μπες στο Language Academy":"📚 Language Academy ξεκλείδωσε"):"🔒 Μετά το History Island";s.classList.toggle("ready",h&&!d);if(d){$("zones").textContent="4/4";$("stars").textContent="4";$("mt").textContent="🏆 World Complete — 4/4 περιοχές";$("ms").textContent="Ολοκλήρωσες τον πρώτο κόσμο του Παίξε & Μάθε."}else if(h&&!near){$("zones").textContent="3/4";$("mt").textContent="🔓 Τελική περιοχή: Language Academy";$("ms").textContent="Πλησίασε τη μωβ πύλη."}}
function open(){$("langModal").hidden=0;$("langIntro").hidden=0;$("langSentence").hidden=1;$("langVerb").hidden=1;$("langCount").textContent="1/3";$("langTitle").textContent="Η βιβλιοθήκη των λέξεων"}
function reset(){words=[];document.querySelectorAll(".word-chip").forEach(b=>b.disabled=0);$("langFb").hidden=$("langReset").hidden=$("langNext").hidden=1;draw()}
function draw(){let e=$("langSeq");e.innerHTML="";if(!words.length){let x=document.createElement("span");x.textContent="Οι λέξεις θα μπουν εδώ";e.appendChild(x)}else words.forEach(w=>{let x=document.createElement("span");x.textContent=w;e.appendChild(x)})}
function pick(b){if(words.length>4)return;words.push(b.dataset.w);b.disabled=1;draw();if(words.length===5){let ok=words.join("|")==="Το|παιδί|διαβάζει|ένα|βιβλίο.";$("langFb").hidden=0;$("langFb").classList.toggle("ok",ok);$("langFt").textContent=ok?"Σωστά!":"Δοκίμασε άλλη σειρά";$("langFp").textContent=ok?"«Το παιδί διαβάζει ένα βιβλίο.»":"Ξεκίνα με «Το παιδί» και μετά σκέψου τι κάνει.";$("langNext").hidden=!ok;$("langReset").hidden=ok}}
function verb(){$("langSentence").hidden=1;$("langVerb").hidden=0;$("langCount").textContent="3/3";$("langTitle").textContent="Βρες το ρήμα";$("verbFb").hidden=$("langFinish").hidden=1;document.querySelectorAll("[data-v]").forEach(b=>b.disabled=0)}
function choose(b){let ok=b.dataset.v==="g";document.querySelectorAll("[data-v]").forEach(x=>x.disabled=1);$("verbFb").hidden=0;$("verbFb").classList.toggle("ok",ok);$("verbFt").textContent=ok?"Σωστά — «γράφει» είναι το ρήμα":"Δοκίμασε ξανά";$("verbFp").textContent=ok?"Το ρήμα δείχνει τι κάνει η Μαρία.":"Ψάξε τη λέξη που δείχνει τη δράση.";$("langFinish").hidden=!ok;if(!ok)setTimeout(()=>{document.querySelectorAll("[data-v]").forEach(x=>x.disabled=0);$("verbFb").hidden=1},800)}
function finish(){localStorage.setItem(K,"done");m.hidden=1;let f=document.createElement("section");f.className="lang-final";f.innerHTML='<div><div class="trophy">🏆</div><div class="eyebrow">WORLD COMPLETE</div><h1>4/4 περιοχές!</h1><p>Ολοκλήρωσες Μαθηματικά, Φυσικές Επιστήμες, Ιστορία και Γλώσσα.</p><button id="langBack" class="btn primary">Επιστροφή στον χάρτη</button></div>';document.body.appendChild(f);$("langBack").onclick=()=>{f.remove();sync()};sync()}
$("langClose").onclick=()=>m.hidden=1;$("langStart").onclick=()=>{$("langIntro").hidden=1;$("langSentence").hidden=0;$("langCount").textContent="2/3";$("langTitle").textContent="Ξαναφτιάξε την πρόταση";reset()};$("langReset").onclick=reset;$("langNext").onclick=verb;$("langFinish").onclick=finish;document.querySelectorAll(".word-chip").forEach(b=>b.onclick=()=>pick(b));document.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>choose(b));["resetAll","again"].forEach(id=>$(id)?.addEventListener("click",()=>localStorage.removeItem(K),{capture:true}));
$("start")?.addEventListener("click",()=>{run=1;P.x=.18;P.y=.72;last=performance.now()});$("back")?.addEventListener("click",()=>setTimeout(()=>{let d=base().done||{};if(d.history)Object.assign(P,{x:.31,y:.43});else if(d.science)Object.assign(P,{x:.38,y:.39});else if(d.math)Object.assign(P,{x:.62,y:.49});sync()},40));$("enter")?.addEventListener("click",e=>{if(near&&hist()&&!done()){e.stopImmediatePropagation();open()}},{capture:true});
addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key==="Enter"&&near){e.preventDefault();open()}});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));document.querySelectorAll(".pad button").forEach(b=>{b.addEventListener("pointerdown",()=>dir=b.dataset.d);["pointerup","pointercancel","pointerleave"].forEach(x=>b.addEventListener(x,()=>{if(dir===b.dataset.d)dir=null}))});
function frame(t){let dt=Math.min(t-last,24),dx=0,dy=0;last=t;if(run){if(keys.has("arrowleft")||keys.has("a")||dir==="left")dx--;if(keys.has("arrowright")||keys.has("d")||dir==="right")dx++;if(keys.has("arrowup")||keys.has("w")||dir==="up")dy--;if(keys.has("arrowdown")||keys.has("s")||dir==="down")dy++;if(dx&&dy){dx*=.707;dy*=.707}let z=.00065*dt;P.x=Math.max(.08,Math.min(.92,P.x+dx*z));P.y=Math.max(.2,Math.min(.9,P.y+dy*z))}let n=hist()&&!done()&&Math.hypot(P.x-.56,(P.y-.76)*1.15)<.13;if(n!==near){near=n;sync();if(near){$("enter").hidden=0;$("enter").textContent="Μπες στο Language Academy"}}requestAnimationFrame(frame)}
const o=new MutationObserver(sync);o.observe($("zones"),{childList:1,subtree:1});o.observe($("mt"),{childList:1,subtree:1});let p=document.querySelector(".intro-card p");if(p)p.innerHTML='Ξεκίνα από το <b>Math City</b>, πέρασε από <b>Science Lab</b> και <b>History Island</b> και ολοκλήρωσε τον κόσμο στο <b>Language Academy</b>.';sync();requestAnimationFrame(frame);
})();