(()=>{"use strict";const $=id=>document.getElementById(id),C=$("c"),g=C.getContext("2d"),S={on:0,i:0,xp:0,stars:0,coins:0,p:{x:.18,y:.72},keys:new Set,dir:null,near:0,last:0,moving:0,sort:[]};const COINS=[{x:.29,y:.69,t:0},{x:.39,y:.62,t:0},{x:.53,y:.58,t:0},{x:.62,y:.55,t:0},{x:.68,y:.62,t:0}];const Q=[
["0,45","0,8",1,.45,.8,"Μην κοιτάς πόσα ψηφία έχει ο αριθμός. Στα δέκατα: 0,45 έχει 4 δέκατα, ενώ 0,8 έχει 8."],
["0,7","0,65",0,.7,.65,"Γράψε 0,7 ως 0,70. Τα 70 εκατοστά είναι περισσότερα από 65."],
["0,09","0,1",1,.09,.1,"Γράψε 0,1 ως 0,10. Τα 10 εκατοστά είναι περισσότερα από τα 9."],
["1,05","1,5",1,1.05,1.5,"Το ακέραιο μέρος είναι ίδιο: 1. Μετά σύγκρινε τα δέκατα: 0 απέναντι σε 5."],
["0,75","0,705",0,.75,.705,"Γράψε 0,75 ως 0,750. Τώρα σύγκρινε 750 χιλιοστά με 705."]
];const P=[["Math City","Μαθηματικά",.74,.56,"#1678ff",1],["Science Lab","Φυσική • Χημεία",.49,.28,"#24b37a",0],["History Island","Ιστορία",.25,.34,"#d98532",0],["Language Academy","Γλώσσα • Αρχαία",.56,.76,"#8c4ed1",0]];
function hud(){$("xp").textContent=S.xp+" XP";$("stars").textContent=S.stars;$("coins").textContent=S.coins}
function size(){let d=Math.min(devicePixelRatio||1,2),r=C.getBoundingClientRect();C.width=r.width*d;C.height=r.height*d;g.setTransform(d,0,0,d,0,0)}
function rr(x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}
function cloud(x,y,s){g.fillStyle="#ffffffd9";[[0,0,24],[28,-8,31],[57,3,22],[31,12,34]].forEach(a=>{g.beginPath();g.arc(x+a[0]*s,y+a[1]*s,a[2]*s,0,7);g.fill()})}
function scene(t){let w=C.clientWidth,h=C.clientHeight;g.fillStyle="#84dbff";g.fillRect(0,0,w,h);cloud(w*.07,h*.18,1.1);cloud(w*.78,h*.2,.9);g.fillStyle="#65954f";g.beginPath();g.moveTo(w*.04,h*.67);g.lineTo(w*.16,h*.24);g.lineTo(w*.48,h*.14);g.lineTo(w*.87,h*.28);g.lineTo(w*.96,h*.67);g.lineTo(w*.8,h*.91);g.lineTo(w*.26,h*.94);g.closePath();g.fill();g.fillStyle="#45ba64";g.beginPath();g.moveTo(w*.07,h*.62);g.lineTo(w*.18,h*.29);g.lineTo(w*.49,h*.19);g.lineTo(w*.83,h*.31);g.lineTo(w*.93,h*.62);g.lineTo(w*.78,h*.84);g.lineTo(w*.28,h*.88);g.closePath();g.fill();g.strokeStyle="#d9c697";g.lineWidth=17;g.lineCap="round";g.beginPath();g.moveTo(w*.17,h*.72);g.quadraticCurveTo(w*.47,h*.62,w*.74,h*.55);g.stroke();g.beginPath();g.moveTo(w*.44,h*.64);g.lineTo(w*.49,h*.30);g.stroke();g.beginPath();g.moveTo(w*.45,h*.65);g.lineTo(w*.56,h*.76);g.stroke();P.forEach(p=>portal(p,w,h,t));coins(w,h,t);waypoint(w,h,t);player(w,h,t)}
function coins(w,h,t){COINS.forEach((c,i)=>{if(c.t)return;let x=c.x*w,y=c.y*h,b=Math.sin(t/260+i)*4;g.save();g.translate(x,y+b);g.fillStyle="#ffd84a";g.strokeStyle="#d59d16";g.lineWidth=3;g.beginPath();g.arc(0,0,12,0,7);g.fill();g.stroke();g.fillStyle="#fff5a6";g.font="900 12px system-ui";g.textAlign="center";g.fillText("★",0,4);g.restore()})}
function waypoint(w,h,t){if(S.stars||S.near)return;let x=.74*w,y=.56*h-132-Math.sin(t/300)*5;g.save();g.translate(x,y);g.fillStyle="#fff";g.shadowColor="#176fff";g.shadowBlur=14;g.beginPath();g.moveTo(-14,-7);g.lineTo(14,-7);g.lineTo(0,12);g.closePath();g.fill();g.restore()}
function toast(txt){let e=$("toast");e.textContent=txt;e.classList.remove("show");requestAnimationFrame(()=>e.classList.add("show"));clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),850)}
function portal(p,w,h,t){let [name,sub,x,y,col,on]=p,px=x*w,py=y*h,pu=1+Math.sin(t/400)*.04;g.save();g.translate(px,py);g.scale(pu,pu);g.shadowColor=col;g.shadowBlur=on?25:8;g.fillStyle=col;rr(-28,-42,56,84,12);g.fill();g.shadowBlur=0;g.fillStyle="#ffffff99";rr(-15,-29,30,58,8);g.fill();g.restore();g.fillStyle="#f2f6fb";rr(px-55,py-82,110,63,14);g.fill();g.fillStyle=col;g.fillRect(px-55,py-82,110,16);g.fillStyle="#2d4c67";g.fillRect(px-10,py-47,20,28);g.fillStyle=col;let ww=Math.max(126,g.measureText(name).width+32);rr(px-ww/2,py-112,ww,39,10);g.fill();g.fillStyle="#fff";g.textAlign="center";g.font="800 15px system-ui";g.fillText(name,px,py-96);g.font="600 10px system-ui";g.fillText(sub,px,py-82);if(name=="Math City"&&S.stars){g.fillStyle="#116b3dcc";rr(px-48,py+48,96,24,9);g.fill();g.fillStyle="#fff";g.font="800 10px system-ui";g.fillText("✓ Ολοκληρώθηκε",px,py+64)}else if(!on){g.fillStyle="#18364dcc";rr(px-48,py+48,96,24,9);g.fill();g.fillStyle="#fff";g.font="800 10px system-ui";g.fillText("Σύντομα",px,py+64)}}
function player(w,h,t){let bob=S.moving?Math.sin(t/95)*2:0,step=S.moving?Math.sin(t/85)*4:0,x=S.p.x*w,y=S.p.y*h+bob;g.fillStyle="#183c5b2e";g.beginPath();g.ellipse(x,y+23,22,9,0,0,7);g.fill();g.fillStyle="#263a53";g.fillRect(x-17,y+8+step,13,27);g.fillRect(x+5,y+8-step,13,27);g.fillStyle="#1678ff";rr(x-24,y-22,48,35,8);g.fill();g.fillStyle="#edb282";rr(x-17,y-54,34,33,8);g.fill();g.fillStyle="#552a17";rr(x-19,y-59,38,12,7);g.fill()}
function move(dt){let dx=0,dy=0,k=S.keys;if(k.has("arrowleft")||k.has("a")||S.dir=="left")dx--;if(k.has("arrowright")||k.has("d")||S.dir=="right")dx++;if(k.has("arrowup")||k.has("w")||S.dir=="up")dy--;if(k.has("arrowdown")||k.has("s")||S.dir=="down")dy++;if(dx&&dy){dx*=.707;dy*=.707}S.moving=!!(dx||dy);let m=.00065*Math.min(dt,24);S.p.x=Math.max(.08,Math.min(.92,S.p.x+dx*m));S.p.y=Math.max(.2,Math.min(.9,S.p.y+dy*m));COINS.forEach(c=>{if(!c.t&&Math.hypot(S.p.x-c.x,(S.p.y-c.y)*1.15)<.055){c.t=1;S.coins++;S.xp+=10;hud();toast("🪙 Νόμισμα! +10 XP")}});let n=Math.hypot(S.p.x-.74,(S.p.y-.56)*1.15)<.13;if(n!=S.near){S.near=n;$("enter").hidden=!n;$("mt").textContent=n?"🎯 Math City βρέθηκε!":S.stars?"🗺️ Εξερεύνησε τον χάρτη":"🎯 Αποστολή: Βρες το Math City";$("ms").textContent=n?"Πάτησε για να ξεκινήσεις την πρόκληση.":S.stars?"Μάζεψε όσα νομίσματα άφησες πίσω.":"Ακολούθησε το μονοπάτι και μάζεψε νομίσματα."}}
function loop(t){if(!S.on)return;move(t-S.last);S.last=t;scene(t);requestAnimationFrame(loop)}
function start(){$("intro").hidden=1;$("world").hidden=0;S.on=1;size();S.last=performance.now();requestAnimationFrame(loop)}
function render(){let q=Q[S.i];$("compare").hidden=0;$("sort").hidden=1;$("qh").textContent="Η Πύλη των Δεκαδικών";$("count").textContent=`Αποστολή ${S.i+1}/6`;$("a").textContent=q[0];$("b").textContent=q[1];$("fb").hidden=$("nl").hidden=$("retry").hidden=$("next").hidden=1;document.querySelectorAll(".door").forEach(b=>{b.disabled=0;b.style.opacity=1})}
function open(){S.i=0;S.sort=[];render();$("modal").hidden=0;$("enter").hidden=1}
function answer(i){let q=Q[S.i],ok=i==q[2];document.querySelectorAll(".door").forEach(b=>b.disabled=1);$("fb").hidden=$("nl").hidden=0;$("fb").classList.toggle("ok",ok);$("fi").textContent=ok?"✅":"💡";$("ft").textContent=ok?"Σωστά!":"Κοίτα ξανά";$("fp").textContent=(ok?"Μπράβο. "+q[q[2]]+" είναι μεγαλύτερο. ":"")+q[5];let mx=Math.max(q[3],q[4])>1?Math.ceil(Math.max(q[3],q[4])):1;$("max").textContent=String(mx).replace(".",",");[["ma",q[3],q[0]],["mb",q[4],q[1]]].forEach(m=>{let e=$(m[0]);e.style.left=(5+m[1]/mx*90)+"%";e.querySelector("em").textContent=m[2]});if(ok){S.xp+=50;hud();$("next").hidden=0}else{$("retry").hidden=0;document.querySelector(`[data-i="${i}"]`).style.opacity=.55}}
function next(){if(++S.i>=Q.length)showSort();else render()}
function showSort(){S.sort=[];$("compare").hidden=1;$("sort").hidden=0;$("qh").textContent="Η Γέφυρα της Σωστής Σειράς";$("count").textContent="Αποστολή 6/6";$("sfb").hidden=$("sortreset").hidden=$("finishbtn").hidden=1;document.querySelectorAll(".sortcard").forEach(b=>b.disabled=0);drawSeq()}
function drawSeq(){let e=$("seq");e.innerHTML="";for(let i=0;i<3;i++){let x=document.createElement("span");x.textContent=S.sort[i]!=null?String(S.sort[i]).replace(".",","):(i+1)+"ο;";e.appendChild(x)}}
function chooseSort(b){if(S.sort.length>=3)return;let v=+b.dataset.v;S.sort.push(v);b.disabled=1;drawSeq();if(S.sort.length===3){let ok=S.sort.every((v,i)=>v==[.09,.8,1.2][i]);$("sfb").hidden=0;$("sfb").classList.toggle("ok",ok);$("sft").textContent=ok?"Η γέφυρα χτίστηκε!":"Η σειρά δεν είναι σωστή ακόμα";$("sfp").textContent=ok?"0,09 < 0,8 < 1,2. Τώρα συγκρίνεις δεκαδικούς με βάση την αξία τους, όχι το πλήθος των ψηφίων.":"Ξεκίνα από τον αριθμό πιο κοντά στο μηδέν. Θυμήσου ότι 0,8 = 0,80.";$("finishbtn").hidden=!ok;$("sortreset").hidden=ok;if(ok){S.xp+=100;S.stars=1;hud()}}}
function resetSort(){S.sort=[];document.querySelectorAll(".sortcard").forEach(b=>b.disabled=0);$("sfb").hidden=$("sortreset").hidden=1;drawSeq()}
function finishGame(){$("modal").hidden=$("world").hidden=1;$("finish").hidden=0;S.on=0;hud()}
function backWorld(){$("finish").hidden=1;$("world").hidden=0;S.p={x:.72,y:.69};S.near=0;$("mt").textContent="🗺️ Math City ολοκληρώθηκε!";$("ms").textContent="Εξερεύνησε τον χάρτη και μάζεψε όσα νομίσματα άφησες πίσω.";$("enter").hidden=1;S.on=1;S.last=performance.now();requestAnimationFrame(loop)}function again(){S.i=S.xp=S.stars=S.coins=0;S.sort=[];COINS.forEach(c=>c.t=0);S.p={x:.18,y:.72};S.near=0;hud();$("finish").hidden=1;$("world").hidden=0;$("enter").hidden=1;S.on=1;S.last=performance.now();requestAnimationFrame(loop)}
$("start").onclick=start;$("how").onclick=()=>{$("help").hidden=!$("help").hidden};$("enter").onclick=open;$("x").onclick=()=>{$("modal").hidden=1;$("enter").hidden=!S.near};$("retry").onclick=render;$("next").onclick=next;$("sortreset").onclick=resetSort;$("finishbtn").onclick=finishGame;$("back").onclick=backWorld;$("again").onclick=again;document.querySelectorAll(".door").forEach(b=>b.onclick=()=>answer(+b.dataset.i));document.querySelectorAll(".sortcard").forEach(b=>b.onclick=()=>chooseSort(b));addEventListener("resize",size);addEventListener("keydown",e=>{if(e.key.startsWith("Arrow"))e.preventDefault();S.keys.add(e.key.toLowerCase());if(e.key=="Enter"&&S.near&&$("modal").hidden)open()});addEventListener("keyup",e=>S.keys.delete(e.key.toLowerCase()));document.querySelectorAll(".pad button").forEach(b=>{b.onpointerdown=e=>{e.preventDefault();S.dir=b.dataset.d};b.onpointerup=b.onpointercancel=b.onpointerleave=e=>{e.preventDefault();if(S.dir==b.dataset.d)S.dir=null}});hud()})();