(()=>{"use strict";
const $=id=>document.getElementById(id),C=$("c"),g=C.getContext("2d");
const AV=[{shirt:"#1b7cff",hair:"#542914",skin:"#e9ad7b"},{shirt:"#8c4ed1",hair:"#2e2042",skin:"#c98d64"},{shirt:"#24b37a",hair:"#1d3557",skin:"#f0bf91"}];
const S={on:false,i:0,xp:0,coins:0,p:{x:.18,y:.72},keys:new Set(),dir:null,last:0,moving:false,near:null,avatar:0,done:{math:false,science:false,history:false},sort:[],circuit:[],timeline:[],historyStep:0};
const COINS=[{x:.29,y:.69,t:0},{x:.39,y:.62,t:0},{x:.53,y:.58,t:0},{x:.62,y:.55,t:0},{x:.68,y:.62,t:0},{x:.55,y:.39,t:0},{x:.33,y:.38,t:0}];
const Q=[["0,45","0,8",1,.45,.8,"Μην κοιτάς πόσα ψηφία έχει ο αριθμός. Στα δέκατα: 0,45 έχει 4 δέκατα, ενώ 0,8 έχει 8."],["0,7","0,65",0,.7,.65,"Γράψε 0,7 ως 0,70. Τα 70 εκατοστά είναι περισσότερα από 65."],["0,09","0,1",1,.09,.1,"Γράψε 0,1 ως 0,10. Τα 10 εκατοστά είναι περισσότερα από τα 9."],["1,05","1,5",1,1.05,1.5,"Το ακέραιο μέρος είναι ίδιο: 1. Μετά σύγκρινε τα δέκατα: 0 απέναντι σε 5."],["0,75","0,705",0,.75,.705,"Γράψε 0,75 ως 0,750. Τώρα σύγκρινε 750 χιλιοστά με 705."]];
const PORTALS=[{key:"math",name:"Math City",sub:"Μαθηματικά",x:.74,y:.56,col:"#1678ff"},{key:"science",name:"Science Lab",sub:"Φυσική • Χημεία",x:.49,y:.28,col:"#24b37a"},{key:"history",name:"History Island",sub:"Ιστορία",x:.25,y:.34,col:"#d98532"},{key:"language",name:"Language Academy",sub:"Γλώσσα • Αρχαία",x:.56,y:.76,col:"#8c4ed1"}];
const unlocked=k=>k==="math"||(k==="science"&&S.done.math)||(k==="history"&&S.done.science);const completed=k=>!!S.done[k];
function save(){try{localStorage.setItem("aitools4kids-play-v3",JSON.stringify({xp:S.xp,coins:S.coins,avatar:S.avatar,done:S.done,collected:COINS.map(c=>c.t)}))}catch{}}
function load(){try{let raw=localStorage.getItem("aitools4kids-play-v3")||localStorage.getItem("aitools4kids-play-v2");let v=JSON.parse(raw||"null");if(!v)return;S.xp=+v.xp||0;S.coins=+v.coins||0;S.avatar=Math.max(0,Math.min(2,+v.avatar||0));S.done={math:!!v.done?.math,science:!!v.done?.science,history:!!v.done?.history};(v.collected||[]).forEach((x,i)=>{if(COINS[i])COINS[i].t=x?1:0})}catch{}}
function stars(){return +(S.done.math)+ +(S.done.science)+ +(S.done.history)}
function hud(){$("xp").textContent=S.xp+" XP";$("coins").textContent=S.coins;$("stars").textContent=stars();$("zones").textContent=stars()+"/3"}
function applyAvatar(){let a=AV[S.avatar];document.documentElement.style.setProperty("--avatar",a.shirt);$("previewHead").style.background=a.skin;$("previewHead").style.borderColor=a.skin;$("previewHair").style.background=a.hair;document.querySelectorAll(".avatar-choice").forEach(b=>b.classList.toggle("selected",+b.dataset.avatar===S.avatar));save()}
function size(){let d=Math.min(devicePixelRatio||1,2),r=C.getBoundingClientRect();C.width=r.width*d;C.height=r.height*d;g.setTransform(d,0,0,d,0,0)}
function rr(x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}
function cloud(x,y,s){g.fillStyle="#ffffffd9";[[0,0,24],[28,-8,31],[57,3,22],[31,12,34]].forEach(a=>{g.beginPath();g.arc(x+a[0]*s,y+a[1]*s,a[2]*s,0,7);g.fill()})}
function scene(t){let w=C.clientWidth,h=C.clientHeight;g.fillStyle="#84dbff";g.fillRect(0,0,w,h);cloud(w*.07,h*.18,1.1);cloud(w*.78,h*.2,.9);g.fillStyle="#65954f";g.beginPath();g.moveTo(w*.04,h*.67);g.lineTo(w*.16,h*.24);g.lineTo(w*.48,h*.14);g.lineTo(w*.87,h*.28);g.lineTo(w*.96,h*.67);g.lineTo(w*.8,h*.91);g.lineTo(w*.26,h*.94);g.closePath();g.fill();g.fillStyle="#45ba64";g.beginPath();g.moveTo(w*.07,h*.62);g.lineTo(w*.18,h*.29);g.lineTo(w*.49,h*.19);g.lineTo(w*.83,h*.31);g.lineTo(w*.93,h*.62);g.lineTo(w*.78,h*.84);g.lineTo(w*.28,h*.88);g.closePath();g.fill();g.strokeStyle="#d9c697";g.lineWidth=17;g.lineCap="round";g.beginPath();g.moveTo(w*.17,h*.72);g.quadraticCurveTo(w*.47,h*.62,w*.74,h*.55);g.stroke();g.beginPath();g.moveTo(w*.44,h*.64);g.lineTo(w*.49,h*.30);g.stroke();g.beginPath();g.moveTo(w*.44,h*.39);g.lineTo(w*.27,h*.35);g.stroke();g.beginPath();g.moveTo(w*.45,h*.65);g.lineTo(w*.56,h*.76);g.stroke();PORTALS.forEach(p=>portal(p,w,h,t));coins(w,h,t);waypoint(w,h,t);player(w,h,t)}
function portal(p,w,h,t){let px=p.x*w,py=p.y*h,on=unlocked(p.key),done=completed(p.key),pulse=1+Math.sin(t/400)*.04;g.save();g.translate(px,py);g.scale(pulse,pulse);g.shadowColor=p.col;g.shadowBlur=on?25:5;g.globalAlpha=on?1:.48;g.fillStyle=p.col;rr(-28,-42,56,84,12);g.fill();g.fillStyle="#ffffff99";rr(-15,-29,30,58,8);g.fill();g.restore();g.globalAlpha=1;g.fillStyle="#f2f6fb";rr(px-58,py-82,116,63,14);g.fill();g.fillStyle=p.col;g.fillRect(px-58,py-82,116,16);g.fillStyle="#2d4c67";g.fillRect(px-10,py-47,20,28);g.fillStyle=p.col;let ww=Math.max(132,g.measureText(p.name).width+32);rr(px-ww/2,py-112,ww,39,10);g.fill();g.fillStyle="#fff";g.textAlign="center";g.font="800 15px system-ui";g.fillText(p.name,px,py-96);g.font="600 10px system-ui";g.fillText(p.sub,px,py-82);let label;if(done)label="✓ Ολοκληρώθηκε";else if(on)label=p.key==="math"?"Ανοιχτό":"Ξεκλείδωσε!";else if(p.key==="science")label="🔒 Μετά το Math City";else if(p.key==="history")label="🔒 Μετά το Science Lab";else label="Σύντομα";g.fillStyle=done?"#116b3dcc":"#18364dcc";rr(px-60,py+48,120,24,9);g.fill();g.fillStyle="#fff";g.font="800 10px system-ui";g.fillText(label,px,py+64)}
function coins(w,h,t){COINS.forEach((c,i)=>{if(c.t)return;let x=c.x*w,y=c.y*h,b=Math.sin(t/260+i)*4;g.save();g.translate(x,y+b);g.fillStyle="#ffd84a";g.strokeStyle="#d59d16";g.lineWidth=3;g.beginPath();g.arc(0,0,12,0,7);g.fill();g.stroke();g.fillStyle="#fff5a6";g.font="900 12px system-ui";g.textAlign="center";g.fillText("★",0,4);g.restore()})}
function targetPortal(){if(!S.done.math)return PORTALS[0];if(!S.done.science)return PORTALS[1];if(!S.done.history)return PORTALS[2];return null}
function waypoint(w,h,t){let target=targetPortal();if(!target||S.near)return;let x=target.x*w,y=target.y*h-132-Math.sin(t/300)*5;g.save();g.translate(x,y);g.fillStyle="#fff";g.shadowColor=target.col;g.shadowBlur=14;g.beginPath();g.moveTo(-14,-7);g.lineTo(14,-7);g.lineTo(0,12);g.closePath();g.fill();g.restore()}
function player(w,h,t){let a=AV[S.avatar],bob=S.moving?Math.sin(t/95)*2:0,step=S.moving?Math.sin(t/85)*4:0,x=S.p.x*w,y=S.p.y*h+bob;g.fillStyle="#183c5b2e";g.beginPath();g.ellipse(x,y+23,22,9,0,0,7);g.fill();g.fillStyle="#263a53";g.fillRect(x-17,y+8+step,13,27);g.fillRect(x+5,y+8-step,13,27);g.fillStyle=a.shirt;rr(x-24,y-22,48,35,8);g.fill();g.fillStyle=a.skin;rr(x-17,y-54,34,33,8);g.fill();g.fillStyle=a.hair;rr(x-19,y-59,38,12,7);g.fill()}
function toast(txt){let e=$("toast");e.textContent=txt;e.classList.remove("show");requestAnimationFrame(()=>e.classList.add("show"));clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),900)}
function updateMission(){if(S.near){let p=PORTALS.find(x=>x.key===S.near);$("mt").textContent="🎯 "+p.name+" βρέθηκε!";$("ms").textContent=completed(p.key)?"Μπορείς να ξαναπαίξεις την περιοχή.":"Πάτησε για να μπεις στην αποστολή.";$("enter").textContent="Μπες στο "+p.name;return}if(!S.done.math){$("mt").textContent="🎯 Αποστολή: Βρες το Math City";$("ms").textContent="Ακολούθησε το μονοπάτι και μάζεψε νομίσματα."}else if(!S.done.science){$("mt").textContent="🔓 Νέα περιοχή: Science Lab";$("ms").textContent="Το εργαστήριο ξεκλείδωσε. Βρες την πράσινη πύλη."}else if(!S.done.history){$("mt").textContent="🔓 Νέα περιοχή: History Island";$("ms").textContent="Το νησί της Ιστορίας άνοιξε. Βρες την πορτοκαλί πύλη."}else{$("mt").textContent="🏆 Τρεις περιοχές ολοκληρώθηκαν!";$("ms").textContent="Ο κόσμος θα συνεχίσει να μεγαλώνει. Το Language Academy έρχεται μετά."}}
function move(dt){let dx=0,dy=0,k=S.keys;if(k.has("arrowleft")||k.has("a")||S.dir==="left")dx--;if(k.has("arrowright")||k.has("d")||S.dir==="right")dx++;if(k.has("arrowup")||k.has("w")||S.dir==="up")dy--;if(k.has("arrowdown")||k.has("s")||S.dir==="down")dy++;if(dx&&dy){dx*=.707;dy*=.707}S.moving=!!(dx||dy);let m=.00065*Math.min(dt,24);S.p.x=Math.max(.08,Math.min(.92,S.p.x+dx*m));S.p.y=Math.max(.2,Math.min(.9,S.p.y+dy*m));COINS.forEach(c=>{if(!c.t&&Math.hypot(S.p.x-c.x,(S.p.y-c.y)*1.15)<.055){c.t=1;S.coins++;S.xp+=10;hud();save();toast("🪙 Νόμισμα! +10 XP")}});let nearest=null,best=.13;PORTALS.forEach(p=>{if(!unlocked(p.key))return;let d=Math.hypot(S.p.x-p.x,(S.p.y-p.y)*1.15);if(d<best){best=d;nearest=p.key}});if(nearest!==S.near){S.near=nearest;$("enter").hidden=!nearest;updateMission()}}
function loop(t){if(!S.on)return;move(t-S.last);S.last=t;scene(t);requestAnimationFrame(loop)}
function start(){$("intro").hidden=true;$("world").hidden=false;S.on=true;size();updateMission();S.last=performance.now();requestAnimationFrame(loop)}
function enterPortal(){if(S.near==="math")openMath();else if(S.near==="science")openScience();else if(S.near==="history")openHistory()}
function openMath(){S.i=0;S.sort=[];renderMath();$("mathModal").hidden=false;$("enter").hidden=true}
function renderMath(){let q=Q[S.i];$("compare").hidden=false;$("sort").hidden=true;$("mathTitle").textContent="Η Πύλη των Δεκαδικών";$("mathCount").textContent=`Αποστολή ${S.i+1}/6`;$("a").textContent=q[0];$("b").textContent=q[1];$("fb").hidden=$("nl").hidden=$("retry").hidden=$("next").hidden=true;document.querySelectorAll(".door").forEach(b=>{b.disabled=false;b.style.opacity=1})}
function answer(i){let q=Q[S.i],ok=i==q[2];document.querySelectorAll(".door").forEach(b=>b.disabled=true);$("fb").hidden=$("nl").hidden=false;$("fb").classList.toggle("ok",ok);$("fi").textContent=ok?"✅":"💡";$("ft").textContent=ok?"Σωστά!":"Κοίτα ξανά";$("fp").textContent=(ok?"Μπράβο. "+q[q[2]]+" είναι μεγαλύτερο. ":"")+q[5];let mx=Math.max(q[3],q[4])>1?Math.ceil(Math.max(q[3],q[4])):1;$("max").textContent=String(mx).replace(".",",");[["ma",q[3],q[0]],["mb",q[4],q[1]]].forEach(m=>{let e=$(m[0]);e.style.left=(5+m[1]/mx*90)+"%";e.querySelector("em").textContent=m[2]});if(ok){S.xp+=50;hud();save();$("next").hidden=false}else{$("retry").hidden=false;document.querySelector(`[data-i="${i}"]`).style.opacity=.55}}
function nextMath(){if(++S.i>=Q.length)showSort();else renderMath()}
function showSort(){S.sort=[];$("compare").hidden=true;$("sort").hidden=false;$("mathTitle").textContent="Η Γέφυρα της Σωστής Σειράς";$("mathCount").textContent="Αποστολή 6/6";$("sfb").hidden=$("sortreset").hidden=$("mathFinish").hidden=true;document.querySelectorAll(".sortcard").forEach(b=>b.disabled=false);drawSeq()}
function drawSeq(){let e=$("seq");e.innerHTML="";for(let i=0;i<3;i++){let x=document.createElement("span");x.textContent=S.sort[i]!=null?String(S.sort[i]).replace(".",","):(i+1)+"ο;";e.appendChild(x)}}
function chooseSort(b){if(S.sort.length>=3)return;let v=+b.dataset.v;S.sort.push(v);b.disabled=true;drawSeq();if(S.sort.length===3){let ok=S.sort.every((v,i)=>v==[.09,.8,1.2][i]);$("sfb").hidden=false;$("sfb").classList.toggle("ok",ok);$("sft").textContent=ok?"Η γέφυρα χτίστηκε!":"Η σειρά δεν είναι σωστή ακόμα";$("sfp").textContent=ok?"0,09 < 0,8 < 1,2. Σύγκρινες τους δεκαδικούς με βάση την αξία τους.":"Ξεκίνα από τον αριθμό πιο κοντά στο μηδέν. Θυμήσου ότι 0,8 = 0,80.";$("mathFinish").hidden=!ok;$("sortreset").hidden=ok;if(ok){S.xp+=100;hud();save()}}}
function resetSort(){S.sort=[];document.querySelectorAll(".sortcard").forEach(b=>b.disabled=false);$("sfb").hidden=$("sortreset").hidden=true;drawSeq()}
function completeMath(){let first=!S.done.math;S.done.math=true;if(first)S.xp+=50;save();hud();$("mathModal").hidden=true;showFinish("Math City ολοκληρώθηκε!","Ξεκλείδωσες το Science Lab.",first?"⚡ +50 XP":"🔁 Επανάληψη")}
function openScience(){resetCircuit();$("scienceCount").textContent="Πείραμα 1/2";$("scienceTitle").textContent="Άναψε τη λάμπα";$("circuitMission").hidden=false;$("conductorMission").hidden=true;$("scienceModal").hidden=false;$("enter").hidden=true}
function resetCircuit(){S.circuit=[];document.querySelectorAll(".lab-item").forEach(b=>{b.disabled=false;b.classList.remove("active","on")});$("lampIcon").textContent="💡";$("circuitFb").hidden=$("circuitReset").hidden=$("scienceNext").hidden=true;drawCircuit()}
function drawCircuit(){let e=$("circuitSeq");e.innerHTML="";const icons={battery:"🔋",wire:"〰️",lamp:"💡",paper:"📄"};for(let i=0;i<3;i++){let s=document.createElement("span");s.textContent=S.circuit[i]?icons[S.circuit[i]]:(i+1);e.appendChild(s)}}
function chooseCircuit(b){if(S.circuit.length>=3)return;S.circuit.push(b.dataset.part);b.disabled=true;b.classList.add("active");drawCircuit();if(S.circuit.length!==3)return;let ok=["battery","wire","lamp"].every(x=>S.circuit.includes(x))&&!S.circuit.includes("paper");$("circuitFb").hidden=false;$("circuitFb").classList.toggle("ok",ok);$("circuitFt").textContent=ok?"Η λάμπα μπορεί να ανάψει!":"Κάτι από τον πάγκο δεν χρειάζεται";$("circuitFp").textContent=ok?"Χρειάζεσαι πηγή ενέργειας, αγώγιμη διαδρομή και συσκευή που χρησιμοποιεί την ενέργεια. Δεν υπάρχει υποχρεωτική σειρά επιλογής.":"Το χαρτί δεν είναι βασικό εξάρτημα του απλού κυκλώματος. Διάλεξε μπαταρία, καλώδιο και λάμπα.";$("scienceNext").hidden=!ok;$("circuitReset").hidden=ok;if(ok){$("lampIcon").textContent="🌟";document.querySelector(".lab-item.lamp").classList.add("on")}}
function nextScience(){$("circuitMission").hidden=true;$("conductorMission").hidden=false;$("scienceCount").textContent="Πείραμα 2/2";$("scienceTitle").textContent="Βρες τον αγωγό";$("materialFb").hidden=true;$("scienceFinish").hidden=true;document.querySelectorAll(".materials button").forEach(b=>{b.disabled=false;b.classList.remove("right","wrong")})}
function chooseMaterial(b){let ok=b.dataset.material==="metal";document.querySelectorAll(".materials button").forEach(x=>x.disabled=true);b.classList.add(ok?"right":"wrong");$("materialFb").hidden=false;$("materialFb").classList.toggle("ok",ok);$("materialIcon").textContent=ok?"✅":"💡";$("materialFt").textContent=ok?"Σωστά — το μέταλλο είναι αγωγός":"Δοκίμασε ξανά";$("materialFp").textContent=ok?"Τα μέταλλα επιτρέπουν στο ηλεκτρικό ρεύμα να περάσει πολύ καλύτερα από το ξύλο ή το πλαστικό.":"Το ξύλο και το πλαστικό χρησιμοποιούνται συνήθως ως μονωτικά. Ψάξε το μεταλλικό αντικείμενο.";$("scienceFinish").hidden=!ok;if(!ok)setTimeout(()=>{document.querySelectorAll(".materials button").forEach(x=>{x.disabled=false;x.classList.remove("wrong")});$("materialFb").hidden=true},900)}
function completeScience(){let first=!S.done.science;S.done.science=true;if(first)S.xp+=150;save();hud();$("scienceModal").hidden=true;showFinish("Science Lab ολοκληρώθηκε!","Ξεκλείδωσες το History Island.",first?"⚡ +150 XP":"🔁 Επανάληψη")}
function openHistory(){S.timeline=[];$("historyModal").hidden=false;$("enter").hidden=true;showHistoryIntro()}
function showHistoryIntro(){$("historyIntro").hidden=false;$("historyTimeline").hidden=true;$("historyArtifact").hidden=true;$("historyCount").textContent="Αποστολή 1/3";$("historyTitle").textContent="Ο φύλακας της Χρονοπύλης";$("npcText").textContent="Η χρονογραμμή του 1821 μπερδεύτηκε. Χρειάζομαι έναν εξερευνητή που θα βάλει ξανά τα γεγονότα στη σωστή θέση."}
function startTimeline(){$("historyIntro").hidden=true;$("historyTimeline").hidden=false;$("historyCount").textContent="Αποστολή 2/3";$("historyTitle").textContent="Επισκεύασε τη χρονογραμμή";S.timeline=[];document.querySelectorAll(".time-stone").forEach(b=>{b.disabled=false;b.classList.remove("chosen")});$("timelineFb").hidden=$("timelineReset").hidden=$("artifactNext").hidden=true;drawTimeline()}
function drawTimeline(){let e=$("timelineSlots");e.innerHTML="";for(let i=0;i<3;i++){let s=document.createElement("span");s.textContent=S.timeline[i]||"?";e.appendChild(s)}}
function chooseTime(b){if(S.timeline.length>=3)return;S.timeline.push(b.dataset.year);b.disabled=true;b.classList.add("chosen");drawTimeline();if(S.timeline.length!==3)return;let ok=S.timeline.join(",")==="1814,1821,1830";$("timelineFb").hidden=false;$("timelineFb").classList.toggle("ok",ok);$("timelineFt").textContent=ok?"Η Χρονοπύλη σταθεροποιήθηκε!":"Η σειρά χρειάζεται διόρθωση";$("timelineFp").textContent=ok?"1814: ιδρύεται η Φιλική Εταιρεία • 1821: ξεκινά η Ελληνική Επανάσταση • 1830: το Πρωτόκολλο του Λονδίνου αναγνωρίζει την Ελλάδα ως ανεξάρτητο κράτος.":"Βάλε τα γεγονότα από το παλαιότερο προς το νεότερο.";$("artifactNext").hidden=!ok;$("timelineReset").hidden=ok}
function resetTimeline(){S.timeline=[];document.querySelectorAll(".time-stone").forEach(b=>{b.disabled=false;b.classList.remove("chosen")});$("timelineFb").hidden=$("timelineReset").hidden=true;drawTimeline()}
function startArtifact(){$("historyTimeline").hidden=true;$("historyArtifact").hidden=false;$("historyCount").textContent="Αποστολή 3/3";$("historyTitle").textContent="Βρες τον αναχρονισμό";$("artifactFb").hidden=$("historyFinish").hidden=true;document.querySelectorAll(".artifact").forEach(b=>{b.disabled=false;b.classList.remove("right","wrong")})}
function chooseArtifact(b){let ok=b.dataset.artifact==="phone";document.querySelectorAll(".artifact").forEach(x=>x.disabled=true);b.classList.add(ok?"right":"wrong");$("artifactFb").hidden=false;$("artifactFb").classList.toggle("ok",ok);$("artifactIcon").textContent=ok?"✅":"🕰️";$("artifactFt").textContent=ok?"Το βρήκες!":"Κοίτα την εποχή";$("artifactFp").textContent=ok?"Ένα σύγχρονο κινητό δεν ανήκει σε σκηνή του 1821. Αυτό λέγεται αναχρονισμός: κάτι τοποθετείται σε εποχή στην οποία δεν υπήρχε.":"Σκέψου ποιο αντικείμενο είναι προϊόν της σύγχρονης τεχνολογίας.";$("historyFinish").hidden=!ok;if(!ok)setTimeout(()=>{document.querySelectorAll(".artifact").forEach(x=>{x.disabled=false;x.classList.remove("wrong")});$("artifactFb").hidden=true},900)}
function completeHistory(){let first=!S.done.history;S.done.history=true;if(first)S.xp+=200;save();hud();$("historyModal").hidden=true;showFinish("History Island ολοκληρώθηκε!","Έμαθες να σκέφτεσαι με χρονογραμμή και να εντοπίζεις αναχρονισμούς.",first?"⚡ +200 XP":"🔁 Επανάληψη")}
function showFinish(title,text,reward){$("world").hidden=true;S.on=false;$("finishTitle").textContent=title;$("finishText").textContent=text;$("finishRewards").innerHTML=`<span>${reward}</span><span>⭐ ${stars()}/3 περιοχές</span>`;$("finish").hidden=false}
function backWorld(){$("finish").hidden=true;$("world").hidden=false;S.near=null;$("enter").hidden=true;if(S.done.history)S.p={x:.31,y:.43};else if(S.done.science)S.p={x:.38,y:.39};else S.p={x:.62,y:.49};S.on=true;updateMission();S.last=performance.now();requestAnimationFrame(loop)}
function resetAll(){if(!confirm("Να μηδενιστεί η πρόοδος του παιχνιδιού σε αυτή τη συσκευή;"))return;try{localStorage.removeItem("aitools4kids-play-v3");localStorage.removeItem("aitools4kids-play-v2")}catch{}S.xp=S.coins=0;S.done={math:false,science:false,history:false};S.avatar=0;S.p={x:.18,y:.72};COINS.forEach(c=>c.t=0);hud();applyAvatar();location.reload()}
function closeModal(id){$(id).hidden=true;$("enter").hidden=!S.near}
load();hud();applyAvatar();
$("start").onclick=start;$("how").onclick=()=>{$("help").hidden=!$("help").hidden};$("resetAll").onclick=resetAll;$("enter").onclick=enterPortal;$("retry").onclick=renderMath;$("next").onclick=nextMath;$("sortreset").onclick=resetSort;$("mathFinish").onclick=completeMath;$("circuitReset").onclick=resetCircuit;$("scienceNext").onclick=nextScience;$("scienceFinish").onclick=completeScience;$("npcContinue").onclick=startTimeline;$("timelineReset").onclick=resetTimeline;$("artifactNext").onclick=startArtifact;$("historyFinish").onclick=completeHistory;$("back").onclick=backWorld;$("again").onclick=resetAll;
document.querySelectorAll(".avatar-choice").forEach(b=>b.onclick=()=>{S.avatar=+b.dataset.avatar;applyAvatar()});document.querySelectorAll(".door").forEach(b=>b.onclick=()=>answer(+b.dataset.i));document.querySelectorAll(".sortcard").forEach(b=>b.onclick=()=>chooseSort(b));document.querySelectorAll(".lab-item").forEach(b=>b.onclick=()=>chooseCircuit(b));document.querySelectorAll(".materials button").forEach(b=>b.onclick=()=>chooseMaterial(b));document.querySelectorAll(".time-stone").forEach(b=>b.onclick=()=>chooseTime(b));document.querySelectorAll(".artifact").forEach(b=>b.onclick=()=>chooseArtifact(b));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
addEventListener("resize",size);addEventListener("keydown",e=>{if(e.key.startsWith("Arrow"))e.preventDefault();S.keys.add(e.key.toLowerCase());if(e.key==="Enter"&&S.near&&document.querySelectorAll(".modal:not([hidden])").length===0)enterPortal()});addEventListener("keyup",e=>S.keys.delete(e.key.toLowerCase()));document.querySelectorAll(".pad button").forEach(b=>{b.onpointerdown=e=>{e.preventDefault();S.dir=b.dataset.d};b.onpointerup=b.onpointercancel=b.onpointerleave=e=>{e.preventDefault();if(S.dir===b.dataset.d)S.dir=null}});
})();